// Interface/web/next/app/login/page.tsx
"use client";

import { useEffect, useState } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { useRouter, usePathname } from "next/navigation";
import Link from "next/link";
import { loginSchema, LoginFormData } from "../../components/lib/validations/schemas";
import { useAuth } from "../../components/contexts/AuthContext";
import '@flaticon/flaticon-uicons/css/all/all.css';

export default function LoginPage() {
	const router = useRouter();
	const pathname = usePathname();
	const { login, user } = useAuth();
	const { loading: authLoading, isAuthenticated } = useAuth();
	const [error, setError] = useState<string>("");
	const [loading, setLoading] = useState(false);

	// Détecter le type d'utilisateur basé sur l'URL
	const getUserTypeFromPath = () => {
		if (pathname.includes('/admin')) return 'director';
		if (pathname.includes('/advisor')) return 'advisor';
		return 'client';
	};

	const userType = getUserTypeFromPath();

	// Configuration des thèmes selon le type d'utilisateur
	const getThemeConfig = () => {
		switch (userType) {
			case 'director':
				return {
					title: 'Administration AVENIR',
					subtitle: 'Connexion directeur',
					gradient: 'from-purple-50 to-purple-100',
					buttonColor: 'bg-purple-600 hover:bg-purple-700',
					ringColor: 'focus:ring-purple-500',
					linkColor: 'text-purple-600 hover:text-purple-700',
					icon: <i className="fi fi-rr-briefcase text-purple-600"></i>
				};
			case 'advisor':
				return {
					title: 'Conseillers AVENIR',
					subtitle: 'Connexion conseiller',
					gradient: 'from-green-50 to-green-100',
					buttonColor: 'bg-green-600 hover:bg-green-700',
					ringColor: 'focus:ring-green-500',
					linkColor: 'text-green-600 hover:text-green-700',
					icon: <i className="fi fi-rr-user-headset text-green-600"></i>
				};
			default:
				return {
					title: 'Banque AVENIR',
					subtitle: 'Connectez-vous à votre compte',
					gradient: 'from-blue-50 to-indigo-100',
					buttonColor: 'bg-blue-600 hover:bg-blue-700',
					ringColor: 'focus:ring-blue-500',
					linkColor: 'text-blue-600 hover:text-blue-700',
					icon: <i className="fi fi-rr-user text-blue-600"></i>
				};
		}
	};

	const theme = getThemeConfig();

	const {
		register,
		handleSubmit,
		formState: { errors },
	} = useForm<LoginFormData>({
		resolver: zodResolver(loginSchema),
	});

	useEffect(() => {
		// Rediriger si déjà authentifié au chargement de la page
		if (!authLoading && isAuthenticated && user) {
			if (user.role === 'director') {
				router.push("/admin/dashboard");
			} else if (user.role === 'advisor') {
				router.push("/advisor/dashboard");
			} else {
				router.push("/dashboard");
			}
		}
	}, [authLoading, isAuthenticated, user, router]);

	const onSubmit = async (data: LoginFormData) => {
		setLoading(true);
		setError("");

		try {
			const result = await login(data.email, data.password);
			// Redirection selon le rôle réel de l'utilisateur
			if (result.role === 'director') {
				router.push("/admin/dashboard");
			} else if (result.role === 'advisor') {
				router.push("/advisor/dashboard");
			} else {
				router.push("/dashboard");
			}
		} catch (err: any) {
			// Afficher l'erreur
			const errorMessage = err.message || "Email ou mot de passe incorrect";
			setError(errorMessage);
			console.error("Erreur de connexion:", err);
		} finally {
			setLoading(false);
		}
	};

	return (
		<div className={`min-h-screen flex items-center justify-center bg-gradient-to-br ${theme.gradient} px-4`}>
			<div className="max-w-md w-full bg-white rounded-2xl shadow-xl p-8">
				<div className="text-center mb-8">
					<h1 className="text-3xl font-bold text-gray-900 mb-2">
						{theme.title}
					</h1>
					<p className="text-gray-600 flex items-center justify-center gap-2">
						{theme.icon}
						{theme.subtitle}
					</p>
				</div>

				{/* Message d'erreur */}
				{error && (
					<div className="mb-4 p-4 bg-red-50 border border-red-200 text-red-700 rounded-lg">
						{error}
					</div>
				)}

				{/* Formulaire */}
				<form onSubmit={handleSubmit(onSubmit)} className="space-y-6">
					{/* Email */}
					<div>
						<label htmlFor="email" className="block text-sm font-medium text-gray-700 mb-1">
							Email
						</label>
						<input
							{...register("email")}
							type="email"
							id="email"
							className={`w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 ${theme.ringColor} focus:border-transparent`}
							placeholder="votre@email.com"
						/>
						{errors.email && (
							<p className="mt-1 text-sm text-red-600">{errors.email.message}</p>
						)}
					</div>

					{/* Mot de passe */}
					<div>
						<label htmlFor="password" className="block text-sm font-medium text-gray-700 mb-1">
							Mot de passe
						</label>
						<input
							{...register("password")}
							type="password"
							id="password"
							className={`w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 ${theme.ringColor} focus:border-transparent`}
							placeholder="••••••••"
						/>
						{errors.password && (
							<p className="mt-1 text-sm text-red-600">{errors.password.message}</p>
						)}
					</div>

					{/* Lien mot de passe oublié */}
					<div className="text-right">
						<Link
							href="/forgot-password"
							className="text-sm text-blue-600 hover:text-blue-700"
						>
							Mot de passe oublié ?
						</Link>
					</div>

					{/* Bouton */}
					<button
						type="submit"
						disabled={loading}
						className={`w-full ${theme.buttonColor} text-white py-3 rounded-lg font-semibold transition-colors disabled:bg-gray-400 disabled:cursor-not-allowed`}
					>
						{loading ? "Connexion..." : "Se connecter"}
					</button>
				</form>

				{/* Lien vers inscription */}
				<p className="mt-6 text-center text-sm text-gray-600">
					Pas encore de compte ?{" "}
					<Link 
						href={userType === 'client' ? '/register' : `/${userType === 'director' ? 'admin' : userType}/register`} 
						className={`${theme.linkColor} font-semibold`}
					>
						S'inscrire
					</Link>
				</p>
			</div>
		</div>
	);
}

// Interface/web/nuxt/pages/admin/login.vue
<template>
  <NuxtLayout name="auth">
    <div class="min-h-screen flex items-center justify-center bg-gradient-to-br from-gray-900 to-gray-800 px-4 py-12">
      <div class="max-w-md w-full">
        <!-- Logo & Title -->
        <div class="text-center mb-8">
          <div class="inline-flex items-center justify-center w-16 h-16 bg-gray-700 rounded-full mb-4">
            <Icon name="heroicons:briefcase" class="w-8 h-8 text-gray-300" />
          </div>
          <h1 class="text-3xl font-bold text-white mb-2">Administration AVENIR</h1>
          <p class="text-gray-400">Espace réservé aux directeurs</p>
        </div>

        <!-- Login Form -->
        <UiCard padding="lg" class="backdrop-blur-sm bg-white/95">
          <UiAlert v-if="error" variant="danger" class="mb-6" :closable="true" @close="error = ''">
            {{ error }}
          </UiAlert>

          <form @submit.prevent="handleSubmit" class="space-y-6">
            <UiInput
              v-model="formData.email"
              label="Email"
              type="email"
              placeholder="directeur@avenir.fr"
              :error="errors.email"
              required
            >
              <template #icon>
                <Icon name="heroicons:envelope" class="w-5 h-5 text-gray-400" />
              </template>
            </UiInput>

            <UiInput
              v-model="formData.password"
              label="Mot de passe"
              type="password"
              placeholder="••••••••"
              :error="errors.password"
              required
            >
              <template #icon>
                <Icon name="heroicons:lock-closed" class="w-5 h-5 text-gray-400" />
              </template>
            </UiInput>

            <UiButton type="submit" variant="primary" size="lg" :loading="loading" class="w-full">
              Se connecter
            </UiButton>
          </form>

          <div class="mt-6 text-center">
            <NuxtLink to="/admin/forgot-password" class="text-sm text-gray-600 hover:text-gray-900">
              Mot de passe oublié ?
            </NuxtLink>
          </div>
        </UiCard>

        <!-- Back to main site -->
        <div class="mt-6 text-center">
          <NuxtLink to="/login" class="text-sm text-gray-400 hover:text-white flex items-center justify-center gap-2">
            <Icon name="heroicons:arrow-left" class="w-4 h-4" />
            Retour à l'espace client
          </NuxtLink>
        </div>
      </div>
    </div>
  </NuxtLayout>
</template>

<script setup lang="ts">
import { loginSchema } from '~/utils/validation';

definePageMeta({
  layout: false,
  middleware: 'guest',
});

const router = useRouter();
const authStore = useAuthStore();
const { login } = useAuth();
const notificationsStore = useNotificationsStore();

const formData = ref({
  email: '',
  password: '',
});

const errors = ref<Record<string, string>>({});
const loading = ref(false);
const error = ref('');

const validateForm = () => {
  errors.value = {};
  const result = loginSchema.safeParse(formData.value);

  if (!result.success) {
    result.error.issues.forEach((issue) => {
      if (issue.path[0]) {
        errors.value[issue.path[0] as string] = issue.message;
      }
    });
    return false;
  }
  return true;
};

const handleSubmit = async () => {
  if (!validateForm()) return;

  loading.value = true;
  error.value = '';

  try {
    await login(formData.value.email, formData.value.password);

    const user = authStore.user;
    if (user?.role !== 'director') {
      error.value = 'Accès réservé aux directeurs uniquement';
      authStore.logout();
      return;
    }

    notificationsStore.addNotification({
      type: 'success',
      message: 'Connexion réussie',
    });

    router.push('/admin/dashboard');
  } catch (err: any) {
    const errorMessage = err.data?.message || err.message || 'Identifiants invalides';
    error.value = errorMessage;
    notificationsStore.addNotification({
      type: 'error',
      message: errorMessage,
    });
  } finally {
    loading.value = false;
  }
};
</script>
