// Interface/web/nuxt/pages/dashboard/transfers/create.vue
<template>
  <div class="min-h-screen bg-gray-50">
    <DashboardHeader />

    <div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
      <!-- Breadcrumb -->
      <nav class="mb-6">
        <ol class="flex items-center space-x-2 text-sm text-gray-600">
          <li>
            <NuxtLink to="/dashboard" class="hover:text-blue-600">Dashboard</NuxtLink>
          </li>
          <li>/</li>
          <li>
            <NuxtLink to="/dashboard/transfers" class="hover:text-blue-600">Transferts</NuxtLink>
          </li>
          <li>/</li>
          <li class="text-gray-900 font-medium">Nouveau transfert</li>
        </ol>
      </nav>

      <!-- Page Header -->
      <div class="mb-8">
        <h1 class="text-3xl font-bold text-gray-900 mb-2">Nouveau transfert</h1>
        <p class="text-gray-600">Effectuez un transfert entre vos comptes ou vers un compte externe</p>
      </div>

      <!-- Transfer Form -->
      <div class="bg-white rounded-2xl shadow-sm border border-gray-200 p-8">
        <form @submit.prevent="handleSubmit" class="space-y-6">
          <!-- Transfer Type Selection -->
          <div>
            <label class="block text-sm font-semibold text-gray-700 mb-3">Type de transfert</label>
            <div class="grid grid-cols-2 gap-4">
              <button
                type="button"
                @click="transferType = 'internal'"
                :class="[
                  'p-4 border-2 rounded-xl transition-all',
                  transferType === 'internal'
                    ? 'border-blue-600 bg-blue-50'
                    : 'border-gray-200 hover:border-gray-300'
                ]"
              >
                <Icon name="material-symbols:swap-horiz" class="text-2xl mb-2" :class="transferType === 'internal' ? 'text-blue-600' : 'text-gray-400'" />
                <div class="font-semibold" :class="transferType === 'internal' ? 'text-blue-600' : 'text-gray-700'">Entre mes comptes</div>
              </button>

              <button
                type="button"
                @click="transferType = 'external'"
                :class="[
                  'p-4 border-2 rounded-xl transition-all',
                  transferType === 'external'
                    ? 'border-purple-600 bg-purple-50'
                    : 'border-gray-200 hover:border-gray-300'
                ]"
              >
                <Icon name="material-symbols:account-balance" class="text-2xl mb-2" :class="transferType === 'external' ? 'text-purple-600' : 'text-gray-400'" />
                <div class="font-semibold" :class="transferType === 'external' ? 'text-purple-600' : 'text-gray-700'">Vers un IBAN externe</div>
              </button>
            </div>
          </div>

          <!-- From Account -->
          <div>
            <label for="fromAccount" class="block text-sm font-semibold text-gray-700 mb-2">
              Compte source
            </label>
            <select
              id="fromAccount"
              v-model="formData.fromAccountId"
              required
              class="w-full px-4 py-3 border border-gray-300 rounded-xl focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
            >
              <option value="">Sélectionnez un compte</option>
              <option v-for="account in accounts" :key="account.id" :value="account.id">
                {{ account.name }} - {{ formatCurrency(account.balance) }} ({{ account.iban }})
              </option>
            </select>
          </div>

          <!-- To Account (Internal) or IBAN (External) -->
          <div v-if="transferType === 'internal'">
            <label for="toAccount" class="block text-sm font-semibold text-gray-700 mb-2">
              Compte destination
            </label>
            <select
              id="toAccount"
              v-model="formData.toAccountId"
              required
              class="w-full px-4 py-3 border border-gray-300 rounded-xl focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
            >
              <option value="">Sélectionnez un compte</option>
              <option
                v-for="account in accounts"
                :key="account.id"
                :value="account.id"
                :disabled="account.id === formData.fromAccountId"
              >
                {{ account.name }} - {{ account.iban }}
              </option>
            </select>
          </div>

          <div v-else>
            <label for="toIban" class="block text-sm font-semibold text-gray-700 mb-2">
              IBAN destination
            </label>
            <input
              id="toIban"
              v-model="formData.toIban"
              type="text"
              required
              placeholder="FR76 1234 5678 9012 3456 7890 123"
              class="w-full px-4 py-3 border border-gray-300 rounded-xl focus:ring-2 focus:ring-purple-500 focus:border-purple-500"
            />
          </div>

          <!-- Amount -->
          <div>
            <label for="amount" class="block text-sm font-semibold text-gray-700 mb-2">
              Montant
            </label>
            <div class="relative">
              <input
                id="amount"
                v-model.number="formData.amount"
                type="number"
                step="0.01"
                min="0.01"
                required
                placeholder="0.00"
                class="w-full px-4 py-3 pr-12 border border-gray-300 rounded-xl focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
              />
              <div class="absolute right-4 top-1/2 -translate-y-1/2 text-gray-500 font-semibold">
                €
              </div>
            </div>
            <p v-if="selectedFromAccount" class="mt-2 text-sm text-gray-500">
              Solde disponible: {{ formatCurrency(selectedFromAccount.balance) }}
            </p>
          </div>

          <!-- Description -->
          <div>
            <label for="description" class="block text-sm font-semibold text-gray-700 mb-2">
              Description (optionnel)
            </label>
            <input
              id="description"
              v-model="formData.description"
              type="text"
              placeholder="Ex: Loyer, Courses, Épargne..."
              class="w-full px-4 py-3 border border-gray-300 rounded-xl focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
            />
          </div>

          <!-- Error Message -->
          <div v-if="error" class="p-4 bg-red-50 border border-red-200 rounded-xl">
            <div class="flex items-center text-red-700">
              <Icon name="material-symbols:error" class="text-xl mr-2" />
              <span>{{ error }}</span>
            </div>
          </div>

          <!-- Success Message -->
          <div v-if="success" class="p-4 bg-green-50 border border-green-200 rounded-xl">
            <div class="flex items-center text-green-700">
              <Icon name="material-symbols:check-circle" class="text-xl mr-2" />
              <span>Transfert effectué avec succès !</span>
            </div>
          </div>

          <!-- Submit Button -->
          <div class="flex gap-4 pt-4">
            <button
              type="submit"
              :disabled="loading"
              class="flex-1 px-6 py-3 bg-gradient-to-r from-blue-600 to-purple-600 text-white rounded-xl font-semibold hover:from-blue-700 hover:to-purple-700 transition-all shadow-lg hover:shadow-xl disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {{ loading ? 'Traitement...' : 'Effectuer le transfert' }}
            </button>
            <NuxtLink
              to="/dashboard/transfers"
              class="px-6 py-3 bg-gray-100 text-gray-700 rounded-xl font-semibold hover:bg-gray-200 transition-all"
            >
              Annuler
            </NuxtLink>
          </div>
        </form>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
const config = useRuntimeConfig()
const router = useRouter()

const transferType = ref<'internal' | 'external'>('internal')
const loading = ref(false)
const error = ref('')
const success = ref(false)

const formData = ref({
  fromAccountId: '',
  toAccountId: '',
  toIban: '',
  amount: 0,
  description: ''
})

const accounts = ref([])

const selectedFromAccount = computed(() => {
  return accounts.value.find((a: any) => a.id === formData.value.fromAccountId)
})

const formatCurrency = (amount: number) => {
  return new Intl.NumberFormat('fr-FR', {
    style: 'currency',
    currency: 'EUR'
  }).format(amount)
}

const loadAccounts = async () => {
  try {
    const token = localStorage.getItem('token')
    const response = await fetch(`${config.public.apiBase}/accounts`, {
      headers: {
        'Authorization': `Bearer ${token}`
      }
    })

    if (response.ok) {
      accounts.value = await response.json()
    }
  } catch (err) {
    console.error('Erreur lors du chargement des comptes:', err)
  }
}

const handleSubmit = async () => {
  error.value = ''
  success.value = false
  loading.value = true

  try {
    const token = localStorage.getItem('token')

    if (transferType.value === 'internal') {
      // Internal transfer
      const response = await fetch(`${config.public.apiBase}/transactions/transfer`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${token}`
        },
        body: JSON.stringify({
          fromAccountId: formData.value.fromAccountId,
          toAccountId: formData.value.toAccountId,
          amount: formData.value.amount,
          description: formData.value.description || 'Transfert interne'
        })
      })

      if (!response.ok) {
        const data = await response.json()
        throw new Error(data.message || 'Erreur lors du transfert')
      }
    } else {
      // External transfer via IBAN
      const response = await fetch(`${config.public.apiBase}/transactions/iban`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${token}`
        },
        body: JSON.stringify({
          fromAccountId: formData.value.fromAccountId,
          toIban: formData.value.toIban,
          amount: formData.value.amount,
          description: formData.value.description || 'Transfert externe'
        })
      })

      if (!response.ok) {
        const data = await response.json()
        throw new Error(data.message || 'Erreur lors du transfert')
      }
    }

    success.value = true

    // Redirect after 2 seconds
    setTimeout(() => {
      router.push('/dashboard/transfers')
    }, 2000)
  } catch (err: any) {
    error.value = err.message || 'Une erreur est survenue'
  } finally {
    loading.value = false
  }
}

onMounted(() => {
  loadAccounts()
})

useSeoMeta({
  title: 'Nouveau transfert - Banque AVENIR',
  description: 'Effectuez un transfert entre vos comptes ou vers un compte externe'
})
</script>

// Interface/web/next/app/dashboard/accounts/create/page.tsx
"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { zodResolver } from "@hookform/resolvers/zod";
import { accountService } from "../../../../components/lib/api/account.service";
import { useAuth } from "../../../../components/contexts/AuthContext";
import '@flaticon/flaticon-uicons/css/all/all.css';

// Schéma de validation
const createAccountSchema = z.object({
	accountName: z
		.string()
		.min(3, "Le nom doit contenir au moins 3 caractères")
		.max(50, "Le nom ne peut pas dépasser 50 caractères"),
	accountType: z.enum(["checking", "savings", "investment"]),
	initialDeposit: z
		.number()
		.min(0, "Le dépôt initial ne peut pas être négatif")
		.optional(),
});

type CreateAccountForm = z.infer<typeof createAccountSchema>;

export default function CreateAccountPage() {
	const router = useRouter();
	const { user, isAuthenticated } = useAuth();
	const [loading, setLoading] = useState(false);
	const [error, setError] = useState<string>("");
	const [success, setSuccess] = useState(false);

	const {
		register,
		handleSubmit,
		watch,
		formState: { errors },
	} = useForm<CreateAccountForm>({
		resolver: zodResolver(createAccountSchema),
		defaultValues: {
			accountType: "checking",
			initialDeposit: 0,
		},
	});

	const selectedType = watch("accountType");

	const onSubmit = async (data: CreateAccountForm) => {
		try {
			setLoading(true);
			setError("");

			if (!isAuthenticated) {
				setError("Vous devez être connecté pour créer un compte");
				setLoading(false);
				return;
			}

			const response = await accountService.create({
				accountName: data.accountName,
				accountType: data.accountType,
				initialDeposit: data.initialDeposit,
			});

			if (response.success) {
				setSuccess(true);
				setTimeout(() => {
					router.push("/dashboard/accounts");
				}, 1500);
			} else {
				setError(response.error || "Erreur lors de la création du compte");
			}
		} catch (err: any) {
			setError(
				err.response?.data?.error || "Impossible de créer le compte"
			);
		} finally {
			setLoading(false);
		}
	};

	const accountTypes = [
		{
			value: "checking",
			label: "Compte Courant",
			description: "Pour vos dépenses quotidiennes et virements",
			icon: <i className="fi fi-rr-credit-card"></i>,
			color: "blue",
		},
		{
			value: "savings",
			label: "Compte Épargne",
			description: "Pour faire fructifier votre argent avec intérêts",
			icon: <i className="fi fi-rr-piggy-bank"></i>,
			color: "green",
		},
		{
			value: "investment",
			label: "Compte Titres",
			description: "Pour investir dans des actions",
			icon: <i className="fi fi-rr-chart-line-up"></i>,
			color: "purple",
		},
	];	if (success) {
		return (
			<div className="min-h-screen flex items-center justify-center bg-gray-50">
				<div className="text-center">
					<div className="w-16 h-16 bg-green-100 rounded-full flex items-center justify-center mx-auto mb-4">
						<i className="fi fi-rr-check text-green-600 text-2xl"></i>
					</div>
					<h2 className="text-2xl font-bold text-gray-900 mb-2">
						Compte créé avec succès !
					</h2>
					<p className="text-gray-600">
						Redirection vers vos comptes...
					</p>
				</div>
			</div>
		);
	}

	return (
		<div className="min-h-screen bg-gray-50 py-8">
			<div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
				{/* Header */}
				<div className="mb-8">
					<Link
						href="/dashboard/accounts"
						className="text-blue-600 hover:text-blue-700 font-medium flex items-center space-x-2 mb-4"
					>
						<i className="fi fi-rr-arrow-left"></i>
						<span>Retour à mes comptes</span>
					</Link>
					<h1 className="text-3xl font-bold text-gray-900">
						Créer un nouveau compte
					</h1>
					<p className="mt-2 text-gray-600">
						Choisissez le type de compte qui correspond à vos besoins
					</p>
				</div>

				{/* Error Message */}
				{error && (
					<div className="mb-6 p-4 bg-red-50 border border-red-200 rounded-lg">
						<p className="text-red-800">{error}</p>
					</div>
				)}

				{/* Form */}
				<form onSubmit={handleSubmit(onSubmit)} className="space-y-6">
					{/* Account Type Selection */}
					<div>
						<label className="block text-sm font-semibold text-gray-900 mb-3">
							Type de compte *
						</label>
						<div className="grid gap-4 md:grid-cols-3">
							{accountTypes.map((type) => (
								<label
									key={type.value}
									className={`relative flex flex-col p-4 border-2 rounded-lg cursor-pointer transition ${
										selectedType === type.value
											? `border-${type.color}-500 bg-${type.color}-50`
											: "border-gray-200 hover:border-gray-300"
									}`}
								>
									<input
										type="radio"
										value={type.value}
										{...register("accountType")}
										className="sr-only"
									/>
									<div className="text-3xl mb-2">{type.icon}</div>
									<div className="font-semibold text-gray-900 mb-1">
										{type.label}
									</div>
									<div className="text-sm text-gray-600">
										{type.description}
									</div>
									{selectedType === type.value && (
										<div className="absolute top-2 right-2">
											<i className={`fi fi-rr-check-circle text-${type.color}-600 text-xl`}></i>
										</div>
									)}
								</label>
							))}
						</div>
						{errors.accountType && (
							<p className="mt-2 text-sm text-red-600">
								{errors.accountType.message}
							</p>
						)}
					</div>

					{/* Account Name */}
					<div>
						<label
							htmlFor="accountName"
							className="block text-sm font-semibold text-gray-900 mb-2"
						>
							Nom personnalisé du compte *
						</label>
						<input
							type="text"
							id="accountName"
							{...register("accountName")}
							placeholder="Ex: Mon compte principal, Épargne vacances..."
							className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
						/>
						{errors.accountName && (
							<p className="mt-2 text-sm text-red-600">
								{errors.accountName.message}
							</p>
						)}
					</div>

					{/* Initial Deposit (Optional) */}
					<div>
						<label
							htmlFor="initialDeposit"
							className="block text-sm font-semibold text-gray-900 mb-2"
						>
							Dépôt initial (optionnel)
						</label>
						<div className="relative">
							<input
								type="number"
								id="initialDeposit"
								step="0.01"
                                max='10000'
								{...register("initialDeposit", { valueAsNumber: true })}
								placeholder="0.00"
								className="w-full px-4 py-3 pr-12 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
							/>
							<div className="absolute inset-y-0 right-0 pr-3 flex items-center pointer-events-none">
								<span className="text-gray-500">€</span>
							</div>
						</div>
						{errors.initialDeposit && (
							<p className="mt-2 text-sm text-red-600">
								{errors.initialDeposit.message}
							</p>
						)}
						<p className="mt-2 text-sm text-gray-600">
							Vous pourrez alimenter votre compte plus tard
						</p>
					</div>

					{/* Submit Button */}
					<div className="flex items-center space-x-4">
						<button
							type="submit"
							disabled={loading}
							className="flex-1 px-6 py-3 bg-gradient-to-r from-blue-600 to-purple-600 text-white rounded-lg hover:from-blue-700 hover:to-purple-700 transition font-semibold disabled:opacity-50 disabled:cursor-not-allowed"
						>
							{loading ? "Création en cours..." : "Créer le compte"}
						</button>
						<Link
							href="/dashboard/accounts"
							className="px-6 py-3 bg-gray-200 text-gray-700 rounded-lg hover:bg-gray-300 transition font-semibold"
						>
							Annuler
						</Link>
					</div>
				</form>

				{/* Info Box */}
				<div className="mt-8 p-4 bg-blue-50 border border-blue-200 rounded-lg">
					<div className="flex items-start space-x-3">
						<i className="fi fi-rr-bulb text-blue-600 text-xl flex-shrink-0 mt-0.5"></i>
						<div>
							<h3 className="font-semibold text-blue-900 mb-1">
								À savoir
							</h3>
							<ul className="text-sm text-blue-800 space-y-1">
								<li>• Un IBAN unique sera automatiquement généré</li>
								<li>• Vous pouvez créer autant de comptes que vous le souhaitez</li>
								<li>• Les comptes épargne bénéficient d'un taux d'intérêt</li>
								<li>• Vous pourrez modifier ou supprimer vos comptes plus tard</li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
	);
}
