// Interface/web/nuxt/pages/investments/orders.vue
<template>
  <NuxtLayout name="dashboard">
    <div class="max-w-7xl mx-auto">
      <h1 class="text-3xl font-bold text-gray-900 mb-8">Historique des ordres</h1>

      <div v-if="loading" class="text-center py-12">
        <Icon name="svg-spinners:ring-resize" class="w-16 h-16 mx-auto mb-4 text-blue-600" />
      </div>

      <div v-else>
        <!-- Filters -->
        <UiCard padding="lg" class="mb-6">
          <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
            <UiInput v-model="filters.orderType" label="Type d'ordre" type="select">
              <select v-model="filters.orderType" class="w-full px-4 py-2 border rounded-lg">
                <option value="">Tous les types</option>
                <option value="BUY">Achat</option>
                <option value="SELL">Vente</option>
              </select>
            </UiInput>

            <UiInput v-model="filters.status" label="Statut" type="select">
              <select v-model="filters.status" class="w-full px-4 py-2 border rounded-lg">
                <option value="">Tous les statuts</option>
                <option value="PENDING">En attente</option>
                <option value="EXECUTED">Exécuté</option>
                <option value="CANCELLED">Annulé</option>
                <option value="FAILED">Échoué</option>
              </select>
            </UiInput>

            <div class="flex items-end">
              <UiButton variant="ghost" @click="resetFilters" class="w-full">
                Réinitialiser les filtres
              </UiButton>
            </div>
          </div>
        </UiCard>

        <!-- Orders Table -->
        <UiCard padding="lg">
          <div v-if="filteredOrders.length === 0" class="text-center py-12">
            <Icon name="heroicons:document-text" class="w-16 h-16 mx-auto mb-4 text-gray-400" />
            <p class="text-gray-600 mb-4">Aucun ordre trouvé</p>
            <UiButton variant="primary" @click="router.push('/investments/stocks')">
              Passer un ordre
            </UiButton>
          </div>

          <div v-else class="overflow-x-auto">
            <table class="min-w-full divide-y divide-gray-200">
              <thead class="bg-gray-50">
                <tr>
                  <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Date
                  </th>
                  <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Action
                  </th>
                  <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Type
                  </th>
                  <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Quantité
                  </th>
                  <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Prix
                  </th>
                  <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Total
                  </th>
                  <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Statut
                  </th>
                  <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Actions
                  </th>
                </tr>
              </thead>
              <tbody class="bg-white divide-y divide-gray-200">
                <tr v-for="order in filteredOrders" :key="order.id">
                  <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                    {{ formatDate(order.createdAt) }}
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap">
                    <div class="font-semibold text-gray-900">{{ order.stock.symbol }}</div>
                    <div class="text-sm text-gray-600">{{ order.stock.name }}</div>
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap">
                    <UiBadge :variant="order.orderType === 'BUY' ? 'primary' : 'danger'">
                      {{ order.orderType === 'BUY' ? 'Achat' : 'Vente' }}
                    </UiBadge>
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap text-gray-900">
                    {{ order.quantity }}
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap text-gray-900">
                    {{ order.price.toFixed(2) }} €
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap font-semibold text-gray-900">
                    {{ order.totalAmount.toFixed(2) }} €
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap">
                    <UiBadge :variant="getStatusVariant(order.status)">
                      {{ getStatusLabel(order.status) }}
                    </UiBadge>
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap">
                    <UiButton
                      variant="ghost"
                      size="sm"
                      @click="viewOrderDetails(order)"
                    >
                      Détails
                    </UiButton>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </UiCard>
      </div>
    </div>

    <!-- Order Details Modal -->
    <UiModal
      v-model="showDetailsModal"
      :title="`Détails de l'ordre #${selectedOrder?.id.slice(0, 8)}`"
    >
      <div v-if="selectedOrder" class="space-y-4">
        <div class="grid grid-cols-2 gap-4">
          <div>
            <p class="text-sm text-gray-600">Date</p>
            <p class="font-semibold">{{ formatDate(selectedOrder.createdAt) }}</p>
          </div>

          <div>
            <p class="text-sm text-gray-600">Statut</p>
            <UiBadge :variant="getStatusVariant(selectedOrder.status)">
              {{ getStatusLabel(selectedOrder.status) }}
            </UiBadge>
          </div>

          <div>
            <p class="text-sm text-gray-600">Action</p>
            <p class="font-semibold">{{ selectedOrder.stock.symbol }}</p>
            <p class="text-sm text-gray-600">{{ selectedOrder.stock.name }}</p>
          </div>

          <div>
            <p class="text-sm text-gray-600">Type</p>
            <UiBadge :variant="selectedOrder.orderType === 'BUY' ? 'primary' : 'danger'">
              {{ selectedOrder.orderType === 'BUY' ? 'Achat' : 'Vente' }}
            </UiBadge>
          </div>

          <div>
            <p class="text-sm text-gray-600">Quantité</p>
            <p class="font-semibold">{{ selectedOrder.quantity }}</p>
          </div>

          <div>
            <p class="text-sm text-gray-600">Prix unitaire</p>
            <p class="font-semibold">{{ selectedOrder.price.toFixed(2) }} €</p>
          </div>

          <div>
            <p class="text-sm text-gray-600">Compte</p>
            <p class="font-semibold">{{ selectedOrder.account?.name || 'N/A' }}</p>
          </div>

          <div>
            <p class="text-sm text-gray-600">Montant total</p>
            <p class="font-semibold text-lg">{{ selectedOrder.totalAmount.toFixed(2) }} €</p>
          </div>
        </div>

        <div v-if="selectedOrder.executedAt" class="bg-gray-50 p-4 rounded-lg">
          <p class="text-sm text-gray-600">Date d'exécution</p>
          <p class="font-semibold">{{ formatDate(selectedOrder.executedAt) }}</p>
        </div>
      </div>

      <template #footer>
        <UiButton variant="ghost" @click="showDetailsModal = false">Fermer</UiButton>
      </template>
    </UiModal>
  </NuxtLayout>
</template>

<script setup lang="ts">
definePageMeta({
  layout: false,
  middleware: 'auth',
});

const router = useRouter();
const { apiFetch } = useApi();
const notificationsStore = useNotificationsStore();

interface Stock {
  id: string;
  symbol: string;
  name: string;
}

interface Account {
  id: string;
  name: string;
}

interface Order {
  id: string;
  stockId: string;
  accountId: string;
  orderType: 'BUY' | 'SELL';
  quantity: number;
  price: number;
  totalAmount: number;
  status: 'PENDING' | 'EXECUTED' | 'CANCELLED' | 'FAILED';
  createdAt: string;
  executedAt?: string;
  stock: Stock;
  account?: Account;
}

const loading = ref(true);
const orders = ref<Order[]>([]);
const filters = ref({
  orderType: '',
  status: '',
});

const showDetailsModal = ref(false);
const selectedOrder = ref<Order | null>(null);

const filteredOrders = computed(() => {
  let result = orders.value;

  if (filters.value.orderType) {
    result = result.filter((o) => o.orderType === filters.value.orderType);
  }

  if (filters.value.status) {
    result = result.filter((o) => o.status === filters.value.status);
  }

  return result;
});

const loadOrders = async () => {
  try {
    loading.value = true;
    const data = await apiFetch<Order[]>('/investment/orders');
    orders.value = data;
  } catch (err: any) {
    notificationsStore.addNotification({
      type: 'error',
      message: err.data?.message || 'Erreur de chargement des ordres',
    });
  } finally {
    loading.value = false;
  }
};

const resetFilters = () => {
  filters.value = {
    orderType: '',
    status: '',
  };
};

const viewOrderDetails = (order: Order) => {
  selectedOrder.value = order;
  showDetailsModal.value = true;
};

const formatDate = (dateString: string) => {
  const date = new Date(dateString);
  return new Intl.DateTimeFormat('fr-FR', {
    dateStyle: 'short',
    timeStyle: 'short',
  }).format(date);
};

const getStatusVariant = (status: string) => {
  switch (status) {
    case 'EXECUTED':
      return 'success';
    case 'PENDING':
      return 'warning';
    case 'CANCELLED':
      return 'secondary';
    case 'FAILED':
      return 'danger';
    default:
      return 'secondary';
  }
};

const getStatusLabel = (status: string) => {
  switch (status) {
    case 'EXECUTED':
      return 'Exécuté';
    case 'PENDING':
      return 'En attente';
    case 'CANCELLED':
      return 'Annulé';
    case 'FAILED':
      return 'Échoué';
    default:
      return status;
  }
};

onMounted(() => {
  loadOrders();
});
</script>

// Interface/web/next/app/investment/orders/page.tsx
"use client";

import '@flaticon/flaticon-uicons/css/all/all.css';
import React, { useState, useEffect } from "react";
import { useAuth } from "../../../components/contexts/AuthContext";
import {
	investmentService,
	InvestmentOrder,
} from "../../../components/lib/api/investment.service";

/**
 * Page d'historique des ordres d'investissement
 */
export default function OrdersPage() {
	const { user } = useAuth();
	const [orders, setOrders] = useState<InvestmentOrder[]>([]);
	const [loading, setLoading] = useState(true);
	const [error, setError] = useState<string | null>(null);
	const [cancellingOrder, setCancellingOrder] = useState<string | null>(null);

	useEffect(() => {
		if (user) {
			loadOrders();
		}
	}, [user]);

	const loadOrders = async () => {
		try {
			setLoading(true);
			setError(null);

			const response = await investmentService.getOrderHistory();
			if (response.success && response.data) {
				setOrders(response.data);
			} else {
				setError(response.message || "Erreur lors du chargement des ordres");
			}
		} catch (err) {
			console.error("Erreur lors du chargement:", err);
			setError("Une erreur inattendue s'est produite");
		} finally {
			setLoading(false);
		}
	};

	const handleCancelOrder = async (orderId: string) => {
		try {
			setCancellingOrder(orderId);
			const response = await investmentService.cancelOrder(orderId);

			if (response.success) {
				// Recharger la liste des ordres
				await loadOrders();
			} else {
				setError(response.message || "Erreur lors de l'annulation");
			}
		} catch (err) {
			console.error("Erreur:", err);
			setError("Une erreur inattendue s'est produite");
		} finally {
			setCancellingOrder(null);
		}
	};

	const getStatusBadge = (status: string) => {
		switch (status) {
			case "pending":
				return (
					<span className='inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-yellow-100 text-yellow-800'>
						En attente
					</span>
				);
			case "executed":
				return (
					<span className='inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-green-100 text-green-800'>
						Exécuté
					</span>
				);
			case "cancelled":
				return (
					<span className='inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-red-100 text-red-800'>
						Annulé
					</span>
				);
			default:
				return (
					<span className='inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-gray-100 text-gray-800'>
						{status}
					</span>
				);
		}
	};

	const getOrderTypeColor = (orderType: string) => {
		return orderType === "buy" ? "text-green-600" : "text-red-600";
	};

	if (!user) {
		return (
			<div className='min-h-screen bg-gray-50 flex items-center justify-center'>
				<div className='text-center'>
					<h2 className='text-2xl font-bold text-gray-900 mb-4'>
						Connexion requise
					</h2>
					<p className='text-gray-600'>
						Vous devez être connecté pour voir vos ordres.
					</p>
				</div>
			</div>
		);
	}

	if (loading) {
		return (
			<div className='min-h-screen bg-gray-50 py-12'>
				<div className='max-w-7xl mx-auto px-4 sm:px-6 lg:px-8'>
					<div className='text-center'>
						<div className='animate-spin rounded-full h-32 w-32 border-b-2 border-blue-600 mx-auto'></div>
						<p className='mt-4 text-gray-600'>Chargement des ordres...</p>
					</div>
				</div>
			</div>
		);
	}

	return (
		<div className='min-h-screen bg-gray-50 py-12'>
			<div className='max-w-7xl mx-auto px-4 sm:px-6 lg:px-8'>
				{/* Header */}
				<div className='text-center mb-12'>
					<h1 className='text-4xl font-bold text-gray-900 mb-4'>
						Historique des Ordres
					</h1>
					<p className='text-xl text-gray-600'>
						Suivez tous vos ordres d'investissement
					</p>
				</div>

				{/* Error Alert */}
			{error && (
				<div className='mb-8 bg-red-50 border border-red-200 rounded-lg p-4'>
					<div className='flex'>
						<div className='flex-shrink-0'>
							<i className='fi fi-rr-cross-circle text-red-400 text-xl'></i>
						</div>
						<div className='ml-3'>
							<p className='text-sm text-red-800'>{error}</p>
						</div>
					</div>
				</div>
			)}				{/* Orders Table */}
				{orders.length > 0 ? (
					<div className='bg-white rounded-xl shadow-lg overflow-hidden'>
						<div className='px-6 py-4 border-b border-gray-200'>
							<h3 className='text-lg font-medium text-gray-900'>
								Mes Ordres ({orders.length})
							</h3>
						</div>
						<div className='overflow-x-auto'>
							<table className='min-w-full divide-y divide-gray-200'>
								<thead className='bg-gray-50'>
									<tr>
										<th className='px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider'>
											Date
										</th>
										<th className='px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider'>
											Action
										</th>
										<th className='px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider'>
											Type
										</th>
										<th className='px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider'>
											Quantité
										</th>
										<th className='px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider'>
											Prix
										</th>
										<th className='px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider'>
											Total
										</th>
										<th className='px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider'>
											Statut
										</th>
										{/* <th className='px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider'>
											Actions
										</th> */}
									</tr>
								</thead>
								<tbody className='bg-white divide-y divide-gray-200'>
									{orders.map((order) => (
										<tr key={order.id} className='hover:bg-gray-50'>
											<td className='px-6 py-4 whitespace-nowrap text-sm text-gray-900'>
												{new Date(order.createdAt).toLocaleDateString("fr-FR")}
												<div className='text-xs text-gray-500'>
													{new Date(order.createdAt).toLocaleTimeString(
														"fr-FR"
													)}
												</div>
											</td>
											<td className='px-6 py-4 whitespace-nowrap'>
												<div className='text-sm font-medium text-gray-900'>
													{order.stockSymbol || `#${order.stockId}`}
												</div>
												{order.companyName && (
													<div className='text-xs text-gray-500'>
														{order.companyName}
													</div>
												)}
											</td>
											<td className='px-6 py-4 whitespace-nowrap'>
												<span
													className={`text-sm font-medium ${getOrderTypeColor(
														order.orderType
													)}`}
												>
													{order.orderType === "buy" ? "Achat" : "Vente"}
												</span>
											</td>
											<td className='px-6 py-4 whitespace-nowrap text-sm text-gray-900'>
												{order.quantity}
											</td>
											<td className='px-6 py-4 whitespace-nowrap text-sm text-gray-900'>
												{order.pricePerShare.formatted}
											</td>
											<td className='px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900'>
												{order.totalAmount.formatted}
												<div className='text-xs text-gray-500'>
													(frais: {order.fees.formatted})
												</div>
											</td>
											<td className='px-6 py-4 whitespace-nowrap'>
												{getStatusBadge(order.status)}
												{order.executedAt && (
													<div className='text-xs text-gray-500 mt-1'>
														Exécuté le{" "}
														{new Date(order.executedAt).toLocaleDateString(
															"fr-FR"
														)}
													</div>
												)}
											</td>
											{/* <td className='px-6 py-4 whitespace-nowrap text-sm font-medium'>
												{order.status === "pending" && (
													<button
														onClick={() => handleCancelOrder(order.id)}
														disabled={cancellingOrder === order.id}
														className='text-red-600 hover:text-red-900 disabled:opacity-50 disabled:cursor-not-allowed'
													>
														{cancellingOrder === order.id
															? "Annulation..."
															: "Annuler"}
													</button>
												)}
											</td> */}
										</tr>
									))}
								</tbody>
							</table>
						</div>
					</div>
				) : (
					<div className='text-center py-12'>
						<i className='fi fi-rr-inbox text-gray-400 text-6xl'></i>
						<h3 className='mt-2 text-sm font-medium text-gray-900'>
							Aucun ordre
						</h3>
						<p className='mt-1 text-sm text-gray-500'>
							Vous n'avez encore passé aucun ordre d'investissement.
						</p>
						<div className='mt-6'>
							<a
								href='/investment/stocks'
								className='inline-flex items-center px-4 py-2 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-blue-600 hover:bg-blue-700'
							>
								Passer mon premier ordre
							</a>
						</div>
					</div>
				)}
			</div>
		</div>
	);
}
