// Interface/web/nuxt/pages/admin/users/index.vue
<template>
  <NuxtLayout name="dashboard">
    <div class="max-w-7xl mx-auto">
      <div class="flex items-center justify-between mb-8">
        <h1 class="text-3xl font-bold text-gray-900">Gestion des utilisateurs</h1>
        <UiButton variant="primary" @click="router.push('/admin/users/create')">
          Créer un utilisateur
        </UiButton>
      </div>

      <!-- Filters -->
      <UiCard padding="lg" class="mb-6">
        <div class="grid grid-cols-1 md:grid-cols-4 gap-4">
          <UiInput v-model="filters.search" label="Rechercher" placeholder="Nom, email...">
            <template #icon>
              <Icon name="heroicons:magnifying-glass" class="w-5 h-5 text-gray-400" />
            </template>
          </UiInput>

          <UiInput v-model="filters.role" label="Rôle" type="select">
            <select v-model="filters.role" class="w-full px-4 py-2 border rounded-lg">
              <option value="">Tous les rôles</option>
              <option value="client">Clients</option>
              <option value="advisor">Conseillers</option>
              <option value="director">Directeurs</option>
            </select>
          </UiInput>

          <UiInput v-model="filters.verified" label="Statut" type="select">
            <select v-model="filters.verified" class="w-full px-4 py-2 border rounded-lg">
              <option value="">Tous</option>
              <option value="true">Vérifiés</option>
              <option value="false">Non vérifiés</option>
            </select>
          </UiInput>

          <div class="flex items-end">
            <UiButton variant="ghost" @click="resetFilters" class="w-full">
              Réinitialiser
            </UiButton>
          </div>
        </div>
      </UiCard>

      <!-- Users Table -->
      <UiCard padding="lg">
        <div v-if="loading" class="text-center py-12">
          <Icon name="svg-spinners:ring-resize" class="w-16 h-16 mx-auto mb-4 text-purple-600" />
        </div>

        <div v-else-if="filteredUsers.length === 0" class="text-center py-12">
          <Icon name="heroicons:users" class="w-16 h-16 mx-auto mb-4 text-gray-400" />
          <p class="text-gray-600">Aucun utilisateur trouvé</p>
        </div>

        <div v-else class="overflow-x-auto">
          <table class="min-w-full divide-y divide-gray-200">
            <thead class="bg-gray-50">
              <tr>
                <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Utilisateur
                </th>
                <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Email
                </th>
                <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Rôle
                </th>
                <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Statut
                </th>
                <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Créé le
                </th>
                <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Actions
                </th>
              </tr>
            </thead>
            <tbody class="bg-white divide-y divide-gray-200">
              <tr v-for="user in paginatedUsers" :key="user.id" class="hover:bg-gray-50">
                <td class="px-6 py-4 whitespace-nowrap">
                  <div class="flex items-center">
                    <div class="w-10 h-10 bg-purple-100 rounded-full flex items-center justify-center">
                      <Icon name="heroicons:user" class="w-5 h-5 text-purple-600" />
                    </div>
                    <div class="ml-4">
                      <div class="font-semibold text-gray-900">
                        {{ user.firstName }} {{ user.lastName }}
                      </div>
                    </div>
                  </div>
                </td>
                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                  {{ user.email }}
                </td>
                <td class="px-6 py-4 whitespace-nowrap">
                  <UiBadge :variant="getRoleBadgeVariant(user.role)">
                    {{ getRoleLabel(user.role) }}
                  </UiBadge>
                </td>
                <td class="px-6 py-4 whitespace-nowrap">
                  <UiBadge :variant="user.isVerified ? 'success' : 'warning'">
                    {{ user.isVerified ? 'Vérifié' : 'Non vérifié' }}
                  </UiBadge>
                </td>
                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                  {{ formatDate(user.createdAt) }}
                </td>
                <td class="px-6 py-4 whitespace-nowrap text-sm">
                  <div class="flex items-center gap-2">
                    <UiButton variant="ghost" size="sm" @click="router.push(`/admin/users/${user.id}`)">
                      Voir
                    </UiButton>
                    <UiButton variant="danger" size="sm" @click="openDeleteModal(user)">
                      Supprimer
                    </UiButton>
                  </div>
                </td>
              </tr>
            </tbody>
          </table>
        </div>

        <!-- Pagination -->
        <div v-if="filteredUsers.length > 0" class="mt-6 flex items-center justify-between">
          <p class="text-sm text-gray-600">
            Affichage {{ (currentPage - 1) * itemsPerPage + 1 }} à
            {{ Math.min(currentPage * itemsPerPage, filteredUsers.length) }} sur
            {{ filteredUsers.length }} utilisateurs
          </p>
          <div class="flex gap-2">
            <UiButton
              variant="ghost"
              size="sm"
              :disabled="currentPage === 1"
              @click="currentPage--"
            >
              Précédent
            </UiButton>
            <UiButton
              variant="ghost"
              size="sm"
              :disabled="currentPage >= totalPages"
              @click="currentPage++"
            >
              Suivant
            </UiButton>
          </div>
        </div>
      </UiCard>
    </div>

    <!-- Delete Confirmation Modal -->
    <UiModal v-model="showDeleteModal" title="Confirmer la suppression">
      <p class="text-gray-700">
        Êtes-vous sûr de vouloir supprimer l'utilisateur
        <strong>{{ selectedUser?.firstName }} {{ selectedUser?.lastName }}</strong> ?
      </p>
      <p class="text-sm text-red-600 mt-2">Cette action est irréversible.</p>

      <template #footer>
        <UiButton variant="ghost" @click="showDeleteModal = false">Annuler</UiButton>
        <UiButton variant="danger" :loading="deleting" @click="deleteUser">
          Supprimer
        </UiButton>
      </template>
    </UiModal>
  </NuxtLayout>
</template>

<script setup lang="ts">
definePageMeta({
  layout: false,
  middleware: ['auth', 'role'],
  role: 'director',
});

const router = useRouter();
const { apiFetch } = useApi();
const notificationsStore = useNotificationsStore();

interface User {
  id: string;
  firstName: string;
  lastName: string;
  email: string;
  role: string;
  isVerified: boolean;
  createdAt: string;
}

const users = ref<User[]>([]);
const loading = ref(true);
const filters = ref({
  search: '',
  role: '',
  verified: '',
});

const currentPage = ref(1);
const itemsPerPage = 10;

const showDeleteModal = ref(false);
const selectedUser = ref<User | null>(null);
const deleting = ref(false);

const filteredUsers = computed(() => {
  let result = users.value;

  if (filters.value.search) {
    const search = filters.value.search.toLowerCase();
    result = result.filter(
      (u) =>
        u.firstName.toLowerCase().includes(search) ||
        u.lastName.toLowerCase().includes(search) ||
        u.email.toLowerCase().includes(search)
    );
  }

  if (filters.value.role) {
    result = result.filter((u) => u.role === filters.value.role);
  }

  if (filters.value.verified !== '') {
    const verified = filters.value.verified === 'true';
    result = result.filter((u) => u.isVerified === verified);
  }

  return result;
});

const totalPages = computed(() => Math.ceil(filteredUsers.value.length / itemsPerPage));

const paginatedUsers = computed(() => {
  const start = (currentPage.value - 1) * itemsPerPage;
  const end = start + itemsPerPage;
  return filteredUsers.value.slice(start, end);
});

const loadUsers = async () => {
  try {
    loading.value = true;
    const data = await apiFetch<User[]>('/admin/users');
    users.value = data;
  } catch (err: any) {
    notificationsStore.addNotification({
      type: 'error',
      message: err.data?.message || 'Erreur de chargement des utilisateurs',
    });
  } finally {
    loading.value = false;
  }
};

const resetFilters = () => {
  filters.value = {
    search: '',
    role: '',
    verified: '',
  };
  currentPage.value = 1;
};

const getRoleBadgeVariant = (role: string) => {
  switch (role) {
    case 'director':
      return 'danger';
    case 'advisor':
      return 'primary';
    default:
      return 'secondary';
  }
};

const getRoleLabel = (role: string) => {
  switch (role) {
    case 'director':
      return 'Directeur';
    case 'advisor':
      return 'Conseiller';
    default:
      return 'Client';
  }
};

const formatDate = (dateString: string) => {
  const date = new Date(dateString);
  return new Intl.DateTimeFormat('fr-FR', {
    dateStyle: 'short',
  }).format(date);
};

const openDeleteModal = (user: User) => {
  selectedUser.value = user;
  showDeleteModal.value = true;
};

const deleteUser = async () => {
  if (!selectedUser.value) return;

  try {
    deleting.value = true;
    await apiFetch(`/admin/users/${selectedUser.value.id}`, {
      method: 'DELETE',
    });

    notificationsStore.addNotification({
      type: 'success',
      message: 'Utilisateur supprimé avec succès',
    });

    users.value = users.value.filter((u) => u.id !== selectedUser.value!.id);
    showDeleteModal.value = false;
  } catch (err: any) {
    notificationsStore.addNotification({
      type: 'error',
      message: err.data?.message || 'Erreur lors de la suppression',
    });
  } finally {
    deleting.value = false;
  }
};

onMounted(() => {
  loadUsers();
});
</script>

// Interface/web/next/app/admin/users/page.tsx
"use client";

import { useState, useEffect } from "react";
import { userService, User } from "../../../components/lib/api/user.service";
import Link from "next/link";

export default function AdminUsersPage() {
	const [users, setUsers] = useState<User[]>([]);
	const [loading, setLoading] = useState(true);
	const [error, setError] = useState<string | null>(null);
	const [deleteModal, setDeleteModal] = useState<{ show: boolean; user: User | null }>({
		show: false,
		user: null,
	});

	useEffect(() => {
		loadUsers();
	}, []);

	const loadUsers = async () => {
		try {
			setLoading(true);
			const response = await userService.getAll();
			if (response.success) {
				setUsers(response.data ?? []);
			} else {
				setError(response.error || "Erreur lors du chargement des utilisateurs");
			}
		} catch (error) {
			setError("Erreur lors du chargement des utilisateurs");
		} finally {
			setLoading(false);
		}
	};

	const handleBanToggle = async (userId: string, isBanned: boolean) => {
		try {
			const response = isBanned 
				? await userService.unban(userId)
				: await userService.ban(userId);
				
			if (response.success) {
				loadUsers(); // Recharger la liste
			} else {
				setError(response.error || "Erreur lors de la modification");
			}
		} catch (error) {
			setError("Erreur lors de la modification");
		}
	};

	const handleDelete = async () => {
		if (!deleteModal.user) return;

		try {
			const response = await userService.delete(deleteModal.user.id);
			if (response.success) {
				setDeleteModal({ show: false, user: null });
				loadUsers(); // Recharger la liste
			} else {
				setError(response.error || "Erreur lors de la suppression");
			}
		} catch (error) {
			setError("Erreur lors de la suppression");
		}
	};

	const getRoleBadge = (role: string) => {
		const colors = {
			client: "bg-blue-100 text-blue-800",
			advisor: "bg-green-100 text-green-800",
			director: "bg-purple-100 text-purple-800",
		};
		return colors[role as keyof typeof colors] || "bg-gray-100 text-gray-800";
	};

	if (loading) {
		return (
			<div className="min-h-screen bg-gradient-to-br from-purple-50 to-indigo-100 p-8">
				<div className="max-w-6xl mx-auto">
					<div className="text-center py-8">
						<div className="animate-spin rounded-full h-12 w-12 border-b-2 border-purple-600 mx-auto"></div>
						<p className="mt-4 text-purple-600">Chargement des utilisateurs...</p>
					</div>
				</div>
			</div>
		);
	}

	return (
		<div className="min-h-screen bg-gradient-to-br from-purple-50 to-indigo-100 p-8">
			<div className="max-w-6xl mx-auto">
				{/* Header */}
				<div className="bg-white rounded-lg shadow-lg p-6 mb-8">
					<div className="flex justify-between items-center">
						<div>
							<h1 className="text-3xl font-bold text-purple-900">
								🎯 Gestion des Utilisateurs
							</h1>
							<p className="text-purple-600 mt-2">
								Administrez les comptes utilisateurs et leurs permissions
							</p>
						</div>
						<Link
							href="/admin/users/create"
							className="bg-purple-600 text-white px-6 py-3 rounded-lg hover:bg-purple-700 transition-colors font-medium"
						>
							➕ Créer un utilisateur
						</Link>
					</div>
				</div>

				{/* Message d'erreur */}
				{error && (
					<div className="bg-red-100 border border-red-300 text-red-700 px-4 py-3 rounded-lg mb-6">
						{error}
					</div>
				)}

				{/* Liste des utilisateurs */}
				<div className="bg-white rounded-lg shadow-lg overflow-hidden">
					<div className="overflow-x-auto">
						<table className="w-full">
							<thead className="bg-purple-600 text-white">
								<tr>
									<th className="px-6 py-4 text-left">Utilisateur</th>
									<th className="px-6 py-4 text-left">Email</th>
									<th className="px-6 py-4 text-left">Rôle</th>
									<th className="px-6 py-4 text-left">Statut</th>
									<th className="px-6 py-4 text-left">Créé le</th>
									<th className="px-6 py-4 text-left">Actions</th>
								</tr>
							</thead>
							<tbody className="divide-y divide-gray-200">
								{users.map((user) => (
									<tr key={user.id} className="hover:bg-purple-50">
										<td className="px-6 py-4">
											<div>
												<div className="font-medium text-gray-900">
													{user.fullName}
												</div>
												<div className="text-sm text-gray-500">
													ID: {user.id.slice(0, 8)}...
												</div>
											</div>
										</td>
										<td className="px-6 py-4">
											<div className="text-gray-900">{user.email}</div>
											{user.phone && (
												<div className="text-sm text-gray-500">{user.phone}</div>
											)}
										</td>
										<td className="px-6 py-4">
											<span
												className={`inline-flex px-2 py-1 text-xs font-semibold rounded-full ${getRoleBadge(
													user.role
												)}`}
											>
												{user.role === "director" && "Directeur"}
												{user.role === "advisor" && "Conseiller"}
												{user.role === "client" && "Client"}
											</span>
										</td>
										<td className="px-6 py-4">
											<div className="space-y-1">
												{user.isBanned ? (
													<span className="inline-flex px-2 py-1 text-xs font-semibold rounded-full bg-red-100 text-red-800">
														🚫 Banni
													</span>
												) : (
													<span className="inline-flex px-2 py-1 text-xs font-semibold rounded-full bg-green-100 text-green-800">
														✅ Actif
													</span>
												)}
												{user.emailVerified ? (
													<span className="inline-flex px-2 py-1 text-xs font-semibold rounded-full bg-blue-100 text-blue-800">
														📧 Vérifié
													</span>
												) : (
													<span className="inline-flex px-2 py-1 text-xs font-semibold rounded-full bg-yellow-100 text-yellow-800">
														⚠️ Non vérifié
													</span>
												)}
											</div>
										</td>
										<td className="px-6 py-4 text-sm text-gray-500">
											{new Date(user.createdAt).toLocaleDateString("fr-FR")}
										</td>
										<td className="px-6 py-4">
											<div className="flex space-x-2">
												<Link
													href={`/admin/users/${user.id}`}
													className="text-purple-600 hover:text-purple-800 text-sm font-medium"
												>
													✏️ Modifier
												</Link>
												<button
													onClick={() => handleBanToggle(user.id, user.isBanned)}
													className={`text-sm font-medium ${
														user.isBanned
															? "text-green-600 hover:text-green-800"
															: "text-orange-600 hover:text-orange-800"
													}`}
												>
													{user.isBanned ? "🔓 Débannir" : "🚫 Bannir"}
												</button>
												<button
													onClick={() => setDeleteModal({ show: true, user })}
													className="text-red-600 hover:text-red-800 text-sm font-medium"
												>
													🗑️ Supprimer
												</button>
											</div>
										</td>
									</tr>
								))}
							</tbody>
						</table>
					</div>

					{users.length === 0 && (
						<div className="text-center py-8 text-gray-500">
							<p>Aucun utilisateur trouvé</p>
						</div>
					)}
				</div>

				{/* Statistiques */}
				<div className="grid grid-cols-1 md:grid-cols-4 gap-6 mt-8">
					<div className="bg-white rounded-lg shadow-lg p-6">
						<div className="text-center">
							<div className="text-3xl font-bold text-purple-600">
								{users.length}
							</div>
							<div className="text-gray-600">Total Utilisateurs</div>
						</div>
					</div>
					<div className="bg-white rounded-lg shadow-lg p-6">
						<div className="text-center">
							<div className="text-3xl font-bold text-blue-600">
								{users.filter((u) => u.role === "client").length}
							</div>
							<div className="text-gray-600">Clients</div>
						</div>
					</div>
					<div className="bg-white rounded-lg shadow-lg p-6">
						<div className="text-center">
							<div className="text-3xl font-bold text-green-600">
								{users.filter((u) => u.role === "advisor").length}
							</div>
							<div className="text-gray-600">Conseillers</div>
						</div>
					</div>
					<div className="bg-white rounded-lg shadow-lg p-6">
						<div className="text-center">
							<div className="text-3xl font-bold text-red-600">
								{users.filter((u) => u.isBanned).length}
							</div>
							<div className="text-gray-600">Bannis</div>
						</div>
					</div>
				</div>
			</div>

			{/* Modal de confirmation de suppression */}
			{deleteModal.show && (
				<div className="fixed inset-0 bg-black/30 backdrop-blur-sm bg-opacity-50 flex items-center justify-center z-50">
					<div className="bg-white rounded-lg p-6 max-w-md w-full mx-4">
						<h3 className="text-lg font-semibold text-gray-900 mb-4">
							Confirmer la suppression
						</h3>
						<p className="text-gray-700 mb-6">
							Êtes-vous sûr de vouloir supprimer l'utilisateur{" "}
							<strong>{deleteModal.user?.fullName}</strong> ? Cette action est
							irréversible.
						</p>
						<div className="flex justify-end space-x-4">
							<button
								onClick={() => setDeleteModal({ show: false, user: null })}
								className="px-4 py-2 text-gray-600 border border-gray-300 rounded-lg hover:bg-gray-50"
							>
								Annuler
							</button>
							<button
								onClick={handleDelete}
								className="px-4 py-2 bg-red-600 text-white rounded-lg hover:bg-red-700"
							>
								Supprimer
							</button>
						</div>
					</div>
				</div>
			)}
		</div>
	);
}
