// Interface/web/next/app/admin/users/create/page.tsx
"use client";

import { useState } from "react";
import { userService, CreateUserDTO } from "../../../../components/lib/api/user.service";
import { useRouter } from "next/navigation";
import Link from "next/link";

export default function CreateUserPage() {
	const router = useRouter();
	const [loading, setLoading] = useState(false);
	const [error, setError] = useState<string | null>(null);
	const [formData, setFormData] = useState<CreateUserDTO>({
		email: "",
		password: "",
		firstName: "",
		lastName: "",
		phoneNumber: "",
		address: "",
		role: "client",
	});

	const handleSubmit = async (e: React.FormEvent) => {
		e.preventDefault();
		setLoading(true);
		setError(null);

		try {
			// Nettoyer les champs optionnels vides
			const cleanData = {
				...formData,
				phoneNumber: formData.phoneNumber?.trim() || undefined,
				address: formData.address?.trim() || undefined,
			};

			const response = await userService.create(cleanData);
			
			if (response.success) {
				router.push("/admin/users");
			} else {
				setError(response.error || "Erreur lors de la création de l'utilisateur");
			}
		} catch (error) {
			setError("Erreur lors de la création de l'utilisateur");
		} finally {
			setLoading(false);
		}
	};

	const handleInputChange = (
		e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>
	) => {
		const { name, value } = e.target;
		setFormData((prev: CreateUserDTO) => ({
			...prev,
			[name]: value,
		}));
	};

	return (
		<div className="min-h-screen bg-gradient-to-br from-purple-50 to-indigo-100 p-8">
			<div className="max-w-2xl mx-auto">
				{/* Header */}
				<div className="bg-white rounded-lg shadow-lg p-6 mb-8">
					<div className="flex items-center justify-between">
						<div>
							<h1 className="text-3xl font-bold text-purple-900">
								➕ Créer un Utilisateur
							</h1>
							<p className="text-purple-600 mt-2">
								Ajoutez un nouvel utilisateur au système
							</p>
						</div>
						<Link
							href="/admin/users"
							className="text-purple-600 hover:text-purple-800 font-medium"
						>
							← Retour à la liste
						</Link>
					</div>
				</div>

				{/* Formulaire */}
				<div className="bg-white rounded-lg shadow-lg p-8">
					{error && (
						<div className="bg-red-100 border border-red-300 text-red-700 px-4 py-3 rounded-lg mb-6">
							{error}
						</div>
					)}

					<form onSubmit={handleSubmit} className="space-y-6">
						{/* Informations de base */}
						<div className="grid grid-cols-1 md:grid-cols-2 gap-6">
							<div>
								<label htmlFor="firstName" className="block text-sm font-medium text-gray-700 mb-2">
									Prénom *
								</label>
								<input
									type="text"
									id="firstName"
									name="firstName"
									required
									value={formData.firstName}
									onChange={handleInputChange}
									className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-purple-500 focus:border-transparent"
									placeholder="John"
								/>
							</div>

							<div>
								<label htmlFor="lastName" className="block text-sm font-medium text-gray-700 mb-2">
									Nom *
								</label>
								<input
									type="text"
									id="lastName"
									name="lastName"
									required
									value={formData.lastName}
									onChange={handleInputChange}
									className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-purple-500 focus:border-transparent"
									placeholder="Doe"
								/>
							</div>
						</div>

						{/* Email */}
						<div>
							<label htmlFor="email" className="block text-sm font-medium text-gray-700 mb-2">
								Email *
							</label>
							<input
								type="email"
								id="email"
								name="email"
								required
								value={formData.email}
								onChange={handleInputChange}
								className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-purple-500 focus:border-transparent"
								placeholder="john.doe@example.com"
							/>
						</div>

						{/* Mot de passe */}
						<div>
							<label htmlFor="password" className="block text-sm font-medium text-gray-700 mb-2">
								Mot de passe *
							</label>
							<input
								type="password"
								id="password"
								name="password"
								required
								value={formData.password}
								onChange={handleInputChange}
								className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-purple-500 focus:border-transparent"
								placeholder="••••••••"
								minLength={6}
							/>
							<p className="text-sm text-gray-500 mt-1">
								Le mot de passe doit contenir au moins 6 caractères
							</p>
						</div>

						{/* Rôle */}
						<div>
							<label htmlFor="role" className="block text-sm font-medium text-gray-700 mb-2">
								Rôle *
							</label>
							<select
								id="role"
								name="role"
								required
								value={formData.role}
								onChange={handleInputChange}
								className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-purple-500 focus:border-transparent"
							>
								<option value="client">👤 Client</option>
								<option value="advisor">🏦 Conseiller</option>
								<option value="director">🎯 Directeur</option>
							</select>
						</div>

						{/* Informations optionnelles */}
						<div className="border-t pt-6">
							<h3 className="text-lg font-medium text-gray-900 mb-4">
								Informations optionnelles
							</h3>
							
							<div className="space-y-4">
								<div>
									<label htmlFor="phoneNumber" className="block text-sm font-medium text-gray-700 mb-2">
										Numéro de téléphone
									</label>
									<input
										type="tel"
										id="phoneNumber"
										name="phoneNumber"
										value={formData.phoneNumber}
										onChange={handleInputChange}
										className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-purple-500 focus:border-transparent"
										placeholder="+33 1 23 45 67 89"
									/>
								</div>

								<div>
									<label htmlFor="address" className="block text-sm font-medium text-gray-700 mb-2">
										Adresse
									</label>
									<textarea
										id="address"
										name="address"
										rows={3}
										value={formData.address}
										onChange={handleInputChange}
										className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-purple-500 focus:border-transparent"
										placeholder="123 Rue de la Paix, 75001 Paris"
									/>
								</div>
							</div>
						</div>

						{/* Boutons */}
						<div className="flex justify-end space-x-4 pt-6 border-t">
							<Link
								href="/admin/users"
								className="px-6 py-2 text-gray-600 border border-gray-300 rounded-lg hover:bg-gray-50 transition-colors"
							>
								Annuler
							</Link>
							<button
								type="submit"
								disabled={loading}
								className="px-6 py-2 bg-purple-600 text-white rounded-lg hover:bg-purple-700 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
							>
								{loading ? (
									<>
										<span className="animate-spin rounded-full h-4 w-4 border-b-2 border-white inline-block mr-2"></span>
										Création...
									</>
								) : (
									"Créer l'utilisateur"
								)}
							</button>
						</div>
					</form>
				</div>

				{/* Aide */}
				<div className="bg-blue-50 border border-blue-200 rounded-lg p-4 mt-6">
					<h4 className="font-medium text-blue-900 mb-2">💡 Informations utiles</h4>
					<ul className="text-sm text-blue-800 space-y-1">
						<li>• L'utilisateur recevra un email pour vérifier son compte</li>
						<li>• Le mot de passe peut être modifié après création</li>
						<li>• Les rôles définissent les permissions d'accès au système</li>
						<li>• Les conseillers peuvent gérer les transactions en attente</li>
						<li>• Les directeurs ont accès à toutes les fonctionnalités administratives</li>
					</ul>
				</div>
			</div>
		</div>
	);
}

// Interface/web/nuxt/pages/admin/users/create.vue
<template>
  <NuxtLayout name="dashboard">
    <div class="max-w-3xl mx-auto">
      <div class="mb-8">
        <NuxtLink
          to="/admin/users"
          class="text-purple-600 hover:text-purple-700 font-medium flex items-center gap-2 mb-4"
        >
          <Icon name="heroicons:arrow-left" class="w-5 h-5" />
          Retour aux utilisateurs
        </NuxtLink>
        <h1 class="text-3xl font-bold text-gray-900">Créer un utilisateur</h1>
      </div>

      <UiAlert v-if="error" variant="danger" class="mb-6" :closable="true" @close="error = ''">
        {{ error }}
      </UiAlert>

      <UiCard padding="lg">
        <form @submit.prevent="handleSubmit" class="space-y-6">
          <!-- Role Selection -->
          <div>
            <label class="block text-sm font-semibold text-gray-900 mb-3">Rôle *</label>
            <div class="grid gap-4 md:grid-cols-3">
              <label
                v-for="role in roles"
                :key="role.value"
                :class="[
                  'relative flex flex-col p-4 border-2 rounded-lg cursor-pointer transition',
                  formData.role === role.value
                    ? `border-${role.color}-500 bg-${role.color}-50`
                    : 'border-gray-200 hover:border-gray-300',
                ]"
              >
                <input
                  type="radio"
                  v-model="formData.role"
                  :value="role.value"
                  class="sr-only"
                />
                <Icon :name="role.icon" class="w-8 h-8 mb-2" :class="`text-${role.color}-600`" />
                <div class="font-semibold text-gray-900 mb-1">{{ role.label }}</div>
                <div class="text-sm text-gray-600">{{ role.description }}</div>
                <Icon
                  v-if="formData.role === role.value"
                  name="heroicons:check-circle"
                  :class="`absolute top-2 right-2 w-6 h-6 text-${role.color}-600`"
                />
              </label>
            </div>
            <p v-if="errors.role" class="mt-2 text-sm text-red-600">{{ errors.role }}</p>
          </div>

          <!-- Personal Information -->
          <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
            <UiInput
              v-model="formData.firstName"
              label="Prénom"
              type="text"
              placeholder="Jean"
              :error="errors.firstName"
              required
            />

            <UiInput
              v-model="formData.lastName"
              label="Nom"
              type="text"
              placeholder="Dupont"
              :error="errors.lastName"
              required
            />
          </div>

          <UiInput
            v-model="formData.email"
            label="Email"
            type="email"
            placeholder="utilisateur@avenir.fr"
            :error="errors.email"
            required
          />

          <UiInput
            v-model="formData.password"
            label="Mot de passe"
            type="password"
            placeholder="••••••••"
            :error="errors.password"
            required
          />

          <UiInput
            v-model="formData.confirmPassword"
            label="Confirmer le mot de passe"
            type="password"
            placeholder="••••••••"
            :error="errors.confirmPassword"
            required
          />

          <!-- Submit -->
          <div class="flex items-center gap-4">
            <UiButton type="submit" variant="primary" size="lg" :loading="loading" class="flex-1">
              Créer l'utilisateur
            </UiButton>
            <UiButton variant="ghost" size="lg" @click="router.push('/admin/users')">
              Annuler
            </UiButton>
          </div>
        </form>
      </UiCard>
    </div>
  </NuxtLayout>
</template>

<script setup lang="ts">
import { z } from 'zod';

definePageMeta({
  layout: false,
  middleware: ['auth', 'role'],
  role: 'director',
});

const router = useRouter();
const { apiFetch } = useApi();
const notificationsStore = useNotificationsStore();

const createUserSchema = z
  .object({
    firstName: z.string().min(2, 'Le prénom doit contenir au moins 2 caractères'),
    lastName: z.string().min(2, 'Le nom doit contenir au moins 2 caractères'),
    email: z.string().email("Format d'email invalide"),
    password: z.string().min(8, 'Le mot de passe doit contenir au moins 8 caractères'),
    confirmPassword: z.string(),
    role: z.enum(['client', 'advisor', 'director']),
  })
  .refine((data) => data.password === data.confirmPassword, {
    message: 'Les mots de passe ne correspondent pas',
    path: ['confirmPassword'],
  });

const formData = ref({
  firstName: '',
  lastName: '',
  email: '',
  password: '',
  confirmPassword: '',
  role: 'client' as 'client' | 'advisor' | 'director',
});

const errors = ref<Record<string, string>>({});
const loading = ref(false);
const error = ref('');

const roles = [
  {
    value: 'client',
    label: 'Client',
    description: 'Utilisateur standard avec accès aux services bancaires',
    icon: 'heroicons:user',
    color: 'blue',
  },
  {
    value: 'advisor',
    label: 'Conseiller',
    description: 'Conseiller bancaire avec accès aux outils de gestion client',
    icon: 'heroicons:user-group',
    color: 'green',
  },
  {
    value: 'director',
    label: 'Directeur',
    description: 'Accès administrateur complet',
    icon: 'heroicons:briefcase',
    color: 'purple',
  },
];

const validateForm = () => {
  errors.value = {};
  const result = createUserSchema.safeParse(formData.value);

  if (!result.success) {
    result.error.issues.forEach((issue) => {
      if (issue.path[0]) {
        errors.value[issue.path[0] as string] = issue.message;
      }
    });
    return false;
  }
  return true;
};

const handleSubmit = async () => {
  if (!validateForm()) return;

  loading.value = true;
  error.value = '';

  try {
    await apiFetch('/admin/users', {
      method: 'POST',
      body: {
        firstName: formData.value.firstName,
        lastName: formData.value.lastName,
        email: formData.value.email,
        password: formData.value.password,
        role: formData.value.role,
      },
    });

    notificationsStore.addNotification({
      type: 'success',
      message: 'Utilisateur créé avec succès',
    });

    router.push('/admin/users');
  } catch (err: any) {
    const errorMessage = err.data?.message || err.message || 'Erreur lors de la création';
    error.value = errorMessage;
    notificationsStore.addNotification({
      type: 'error',
      message: errorMessage,
    });
  } finally {
    loading.value = false;
  }
};
</script>
