// Interface/web/next/app/investment/portfolio/page.tsx
"use client";

import '@flaticon/flaticon-uicons/css/all/all.css';
import React, { useState, useEffect } from "react";
import { useAuth } from "../../../components/contexts/AuthContext";
import {
	investmentService,
	Portfolio,
	Position,
} from "../../../components/lib/api/investment.service";

/**
 * Page du portefeuille d'investissement
 */
export default function PortfolioPage() {
	const { user } = useAuth();
	const [portfolio, setPortfolio] = useState<Portfolio | null>(null);
	const [loading, setLoading] = useState(true);
	const [error, setError] = useState<string | null>(null);


	useEffect(() => {
		if (user) {
			loadPortfolio(true); // premier chargement avec loader
			const interval = setInterval(() => {
				loadPortfolio(false); // rafraîchissement invisible
			}, 5000); // 5 secondes
			return () => clearInterval(interval);
		}
	}, [user]);

	const loadPortfolio = async (showLoader = false) => {
		try {
			if (showLoader) setLoading(true);
			setError(null);

			const response = await investmentService.getPortfolio();
			if (response.success && response.data) {
				setPortfolio(response.data);
			} else {
				setError(
					response.message || "Erreur lors du chargement du portefeuille"
				);
			}
		} catch (err) {
			console.error("Erreur lors du chargement:", err);
			setError("Une erreur inattendue s'est produite");
		} finally {
			if (showLoader) setLoading(false);
		}
	};

	const formatPercentage = (percentage: number) => {
		const sign = percentage >= 0 ? "+" : "";
		return `${sign}${percentage.toFixed(2)}%`;
	};

	const getGainLossColor = (amount: number) => {
		if (amount > 0) return "text-green-600";
		if (amount < 0) return "text-red-600";
		return "text-gray-600";
	};

	if (!user) {
		return (
			<div className='min-h-screen bg-gray-50 flex items-center justify-center'>
				<div className='text-center'>
					<h2 className='text-2xl font-bold text-gray-900 mb-4'>
						Connexion requise
					</h2>
					<p className='text-gray-600'>
						Vous devez être connecté pour voir votre portefeuille.
					</p>
				</div>
			</div>
		);
	}

	if (loading) {
		return (
			<div className='min-h-screen bg-gray-50 py-12'>
				<div className='max-w-7xl mx-auto px-4 sm:px-6 lg:px-8'>
					<div className='text-center'>
						<div className='animate-spin rounded-full h-32 w-32 border-b-2 border-blue-600 mx-auto'></div>
						<p className='mt-4 text-gray-600'>Chargement du portefeuille...</p>
					</div>
				</div>
			</div>
		);
	}

	return (
		<div className='min-h-screen bg-gray-50 py-12'>
			<div className='max-w-7xl mx-auto px-4 sm:px-6 lg:px-8'>
				{/* Header */}
				<div className='text-center mb-12'>
					<h1 className='text-4xl font-bold text-gray-900 mb-4'>
						Mon Portefeuille
					</h1>
					<p className='text-xl text-gray-600'>
						Suivez la performance de vos investissements
					</p>
				</div>

				{/* Error Alert */}
			{error && (
				<div className='mb-8 bg-red-50 border border-red-200 rounded-lg p-4'>
					<div className='flex'>
						<div className='shrink-0'>
							<i className='fi fi-rr-cross-circle text-red-400 text-xl'></i>
						</div>
						<div className='ml-3'>
							<p className='text-sm text-red-800'>{error}</p>
						</div>
					</div>
				</div>
			)}				{portfolio ? (
					<>
						{/* Portfolio Summary */}
						<div className='grid grid-cols-1 md:grid-cols-3 gap-6 mb-12'>
							<div className='bg-white rounded-xl shadow-lg p-6'>
								<div className='flex items-center'>
								<div className='shrink-0'>
									<div className='w-8 h-8 bg-blue-600 rounded-lg flex items-center justify-center'>
										<i className='fi fi-rr-wallet text-white text-xl'></i>
									</div>
								</div>
								<div className='ml-5'>
										<p className='text-sm font-medium text-gray-500'>
											Valeur totale
										</p>
										<p className='text-2xl font-bold text-gray-900'>
											{portfolio.totalValue.formatted}
										</p>
									</div>
								</div>
							</div>

							<div className='bg-white rounded-xl shadow-lg p-6'>
								<div className='flex items-center'>
									<div className='shrink-0'>
										<div
											className={`w-8 h-8 rounded-lg flex items-center justify-center ${
												portfolio.totalGainLoss.amount >= 0
													? "bg-green-600"
													: "bg-red-600"
											}`}
										>
											<i className={`text-white text-xl ${
												portfolio.totalGainLoss.amount >= 0
													? 'fi fi-rr-arrow-trend-up'
													: 'fi fi-rr-arrow-trend-down'
											}`}></i>
										</div>
									</div>
									<div className='ml-5'>
										<p className='text-sm font-medium text-gray-500'>
											Gain/Perte
										</p>
										<p
											className={`text-2xl font-bold ${getGainLossColor(
												portfolio.totalGainLoss.amount
											)}`}
										>
											{portfolio.totalGainLoss.formatted}
										</p>
									</div>
								</div>
							</div>

							<div className='bg-white rounded-xl shadow-lg p-6'>
								<div className='flex items-center'>
									<div className='shrink-0'>
										<div
											className={`w-8 h-8 rounded-lg flex items-center justify-center ${
												portfolio.totalGainLossPercentage >= 0
													? "bg-green-600"
													: "bg-red-600"
											}`}
										>
											<i className='fi fi-rr-chart-histogram text-white text-xl'></i>
										</div>
									</div>
									<div className='ml-5'>
										<p className='text-sm font-medium text-gray-500'>
											Performance
										</p>
										<p
											className={`text-2xl font-bold ${getGainLossColor(
												portfolio.totalGainLossPercentage
											)}`}
										>
											{formatPercentage(portfolio.totalGainLossPercentage)}
										</p>
									</div>
								</div>
							</div>
						</div>

						{/* Positions */}
						{portfolio.positions.length > 0 ? (
							<div className='bg-white rounded-xl shadow-lg overflow-hidden'>
								<div className='px-6 py-4 border-b border-gray-200'>
									<h3 className='text-lg font-medium text-gray-900'>
										Mes Positions
									</h3>
									<p className='text-sm text-gray-500'>
										Dernière mise à jour:{" "}
										{new Date(portfolio.lastUpdated).toLocaleString("fr-FR")}
									</p>
								</div>
								<div className='overflow-x-auto'>
									<table className='min-w-full divide-y divide-gray-200'>
										<thead className='bg-gray-50'>
											<tr>
												<th className='px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider'>
													Action
												</th>
												<th className='px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider'>
													Quantité
												</th>
												<th className='px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider'>
													Prix d'achat moyen
												</th>
												<th className='px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider'>
													Prix actuel
												</th>
												<th className='px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider'>
													Valeur totale
												</th>
												<th className='px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider'>
													Gain/Perte
												</th>
												<th className='px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider'>
													Performance
												</th>
											</tr>
										</thead>
										<tbody className='bg-white divide-y divide-gray-200'>
											{portfolio.positions.map((position: Position) => (
												<tr key={position.stockId} className='hover:bg-gray-50'>
													<td className='px-6 py-4 whitespace-nowrap'>
														<div>
															<div className='text-sm font-medium text-gray-900'>
																{position.stockSymbol}
															</div>
															<div className='text-sm text-gray-500'>
																{position.companyName}
															</div>
														</div>
													</td>
													<td className='px-6 py-4 whitespace-nowrap text-sm text-gray-900'>
														{position.quantity}
													</td>
													<td className='px-6 py-4 whitespace-nowrap text-sm text-gray-900'>
														{position.averagePurchasePrice.formatted}
													</td>
													<td className='px-6 py-4 whitespace-nowrap text-sm text-gray-900'>
														{position.currentPrice.formatted}
													</td>
													<td className='px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900'>
														{position.totalValue.formatted}
													</td>
													<td
														className={`px-6 py-4 whitespace-nowrap text-sm font-medium ${getGainLossColor(
															position.gainLoss.amount
														)}`}
													>
														{position.gainLoss.formatted}
													</td>
													<td
														className={`px-6 py-4 whitespace-nowrap text-sm font-medium ${getGainLossColor(
															position.gainLossPercentage
														)}`}
													>
														{formatPercentage(position.gainLossPercentage)}
													</td>
												</tr>
											))}
										</tbody>
									</table>
								</div>
							</div>
						) : (
						<div className='text-center py-12'>
							<i className='fi fi-rr-inbox text-gray-400 text-6xl block mb-4'></i>
								<h3 className='mt-2 text-sm font-medium text-gray-900'>
									Aucune position
								</h3>
								<p className='mt-1 text-sm text-gray-500'>
									Vous n'avez actuellement aucune position dans votre
									portefeuille.
								</p>
								<div className='mt-6'>
									<a
										href='/investment/stocks'
										className='inline-flex items-center px-4 py-2 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-blue-600 hover:bg-blue-700'
									>
										Découvrir les actions
									</a>
								</div>
							</div>
						)}
					</>
				) : (
					<div className='text-center py-12'>
						<i className='fi fi-rr-triangle-warning text-gray-400 text-6xl block mb-4'></i>
						<h3 className='mt-2 text-sm font-medium text-gray-900'>
							Erreur de chargement
						</h3>
						<p className='mt-1 text-sm text-gray-500'>
							Impossible de charger votre portefeuille.
						</p>
						<div className='mt-6'>
							<button
								onClick={() => loadPortfolio(true)}
								className='inline-flex items-center px-4 py-2 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-blue-600 hover:bg-blue-700'
							>
								Réessayer
							</button>
						</div>
					</div>
				)}
			</div>
		</div>
	);
}

// Interface/web/nuxt/pages/investments/portfolio.vue
<template>
  <NuxtLayout name="dashboard">
    <div class="max-w-7xl mx-auto">
      <h1 class="text-3xl font-bold text-gray-900 mb-8">Mon Portefeuille</h1>

      <div v-if="loading" class="text-center py-12">
        <Icon name="svg-spinners:ring-resize" class="w-16 h-16 mx-auto mb-4 text-blue-600" />
      </div>

      <div v-else>
        <!-- Portfolio Summary -->
        <div class="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
          <UiCard padding="lg">
            <p class="text-sm text-gray-600 mb-1">Valeur totale</p>
            <p class="text-3xl font-bold text-gray-900">
              {{ portfolioSummary.totalValue.toFixed(2) }} €
            </p>
          </UiCard>

          <UiCard padding="lg">
            <p class="text-sm text-gray-600 mb-1">Investissement total</p>
            <p class="text-3xl font-bold text-gray-900">
              {{ portfolioSummary.totalInvested.toFixed(2) }} €
            </p>
          </UiCard>

          <UiCard padding="lg">
            <p class="text-sm text-gray-600 mb-1">Gain/Perte total</p>
            <p
              :class="[
                'text-3xl font-bold',
                portfolioSummary.totalGainLoss >= 0 ? 'text-green-600' : 'text-red-600',
              ]"
            >
              {{ portfolioSummary.totalGainLoss >= 0 ? '+' : '' }}{{ portfolioSummary.totalGainLoss.toFixed(2) }} €
            </p>
            <UiBadge
              :variant="portfolioSummary.totalGainLossPercent >= 0 ? 'success' : 'danger'"
              class="mt-2"
            >
              {{ portfolioSummary.totalGainLossPercent >= 0 ? '+' : '' }}{{ portfolioSummary.totalGainLossPercent.toFixed(2) }}%
            </UiBadge>
          </UiCard>
        </div>

        <!-- Positions -->
        <UiCard padding="lg">
          <h2 class="text-xl font-bold text-gray-900 mb-6">Mes positions</h2>

          <div v-if="positions.length === 0" class="text-center py-12">
            <Icon name="heroicons:chart-bar" class="w-16 h-16 mx-auto mb-4 text-gray-400" />
            <p class="text-gray-600 mb-4">Vous n'avez aucune position pour le moment</p>
            <UiButton variant="primary" @click="router.push('/investments/stocks')">
              Explorer les actions
            </UiButton>
          </div>

          <div v-else class="overflow-x-auto">
            <table class="min-w-full divide-y divide-gray-200">
              <thead class="bg-gray-50">
                <tr>
                  <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Action
                  </th>
                  <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Quantité
                  </th>
                  <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Prix d'achat moyen
                  </th>
                  <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Prix actuel
                  </th>
                  <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Valeur totale
                  </th>
                  <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Gain/Perte
                  </th>
                  <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Actions
                  </th>
                </tr>
              </thead>
              <tbody class="bg-white divide-y divide-gray-200">
                <tr v-for="position in positions" :key="position.id">
                  <td class="px-6 py-4 whitespace-nowrap">
                    <div class="font-semibold text-gray-900">{{ position.stock.symbol }}</div>
                    <div class="text-sm text-gray-600">{{ position.stock.name }}</div>
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap text-gray-900">
                    {{ position.quantity }}
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap text-gray-900">
                    {{ position.averageBuyPrice.toFixed(2) }} €
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap">
                    <div class="font-semibold text-gray-900">
                      {{ position.stock.currentPrice.toFixed(2) }} €
                    </div>
                    <UiBadge
                      :variant="position.stock.change >= 0 ? 'success' : 'danger'"
                      size="sm"
                    >
                      {{ position.stock.change >= 0 ? '+' : '' }}{{ position.stock.change.toFixed(2) }}%
                    </UiBadge>
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap font-semibold text-gray-900">
                    {{ position.currentValue.toFixed(2) }} €
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap">
                    <div
                      :class="[
                        'font-semibold',
                        position.gainLoss >= 0 ? 'text-green-600' : 'text-red-600',
                      ]"
                    >
                      {{ position.gainLoss >= 0 ? '+' : '' }}{{ position.gainLoss.toFixed(2) }} €
                    </div>
                    <div
                      :class="[
                        'text-sm',
                        position.gainLossPercent >= 0 ? 'text-green-600' : 'text-red-600',
                      ]"
                    >
                      {{ position.gainLossPercent >= 0 ? '+' : '' }}{{ position.gainLossPercent.toFixed(2) }}%
                    </div>
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap">
                    <UiButton
                      variant="danger"
                      size="sm"
                      @click="openSellModal(position)"
                    >
                      Vendre
                    </UiButton>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </UiCard>
      </div>
    </div>

    <!-- Sell Modal -->
    <UiModal
      v-model="showSellModal"
      :title="`Vendre ${selectedPosition?.stock.symbol}`"
    >
      <div v-if="selectedPosition" class="space-y-4">
        <div>
          <p class="text-sm text-gray-600">Prix actuel</p>
          <p class="text-2xl font-bold">{{ selectedPosition.stock.currentPrice.toFixed(2) }} €</p>
        </div>

        <div>
          <p class="text-sm text-gray-600">Quantité détenue</p>
          <p class="text-lg font-semibold">{{ selectedPosition.quantity }}</p>
        </div>

        <UiInput
          v-model="sellAccountId"
          label="Compte d'investissement"
          type="select"
        >
          <select v-model="sellAccountId" class="w-full px-4 py-2 border rounded-lg">
            <option value="">Sélectionnez un compte</option>
            <option v-for="acc in accounts" :key="acc.id" :value="acc.id">
              {{ acc.name }} - {{ acc.balance.toFixed(2) }} €
            </option>
          </select>
        </UiInput>

        <UiInput
          v-model="sellQuantity"
          label="Quantité à vendre"
          type="number"
          min="1"
          :max="selectedPosition.quantity"
        />

        <div class="bg-gray-50 p-4 rounded-lg">
          <div class="flex justify-between mb-2">
            <span>Sous-total</span>
            <span>{{ (selectedPosition.stock.currentPrice * Number(sellQuantity)).toFixed(2) }} €</span>
          </div>
          <div class="flex justify-between mb-2">
            <span>Frais</span>
            <span>{{ transactionFee.toFixed(2) }} €</span>
          </div>
          <div class="flex justify-between font-bold text-lg">
            <span>Total</span>
            <span>{{ ((selectedPosition.stock.currentPrice * Number(sellQuantity)) - transactionFee).toFixed(2) }} €</span>
          </div>
        </div>
      </div>

      <template #footer>
        <UiButton variant="ghost" @click="showSellModal = false">Annuler</UiButton>
        <UiButton
          variant="danger"
          :loading="sellLoading"
          @click="handleSell"
        >
          Confirmer la vente
        </UiButton>
      </template>
    </UiModal>
  </NuxtLayout>
</template>

<script setup lang="ts">
definePageMeta({
  layout: false,
  middleware: 'auth',
});

const router = useRouter();
const { apiFetch } = useApi();
const notificationsStore = useNotificationsStore();

interface Stock {
  id: string;
  symbol: string;
  name: string;
  currentPrice: number;
  change: number;
}

interface Position {
  id: string;
  stockId: string;
  quantity: number;
  averageBuyPrice: number;
  currentValue: number;
  gainLoss: number;
  gainLossPercent: number;
  stock: Stock;
}

interface Account {
  id: string;
  name: string;
  balance: number;
  type: string;
}

const loading = ref(true);
const positions = ref<Position[]>([]);
const accounts = ref<Account[]>([]);
const portfolioSummary = ref({
  totalValue: 0,
  totalInvested: 0,
  totalGainLoss: 0,
  totalGainLossPercent: 0,
});

const showSellModal = ref(false);
const selectedPosition = ref<Position | null>(null);
const sellAccountId = ref('');
const sellQuantity = ref(1);
const sellLoading = ref(false);
const transactionFee = ref(1);

const loadData = async () => {
  try {
    loading.value = true;

    const [portfolioData, accountsData] = await Promise.all([
      apiFetch<{
        positions: Position[];
        summary: {
          totalValue: number;
          totalInvested: number;
          totalGainLoss: number;
          totalGainLossPercent: number;
        };
      }>('/investment/portfolio'),
      apiFetch<Account[]>('/accounts'),
    ]);

    positions.value = portfolioData.positions;
    portfolioSummary.value = portfolioData.summary;

    const investmentAccounts = accountsData.filter((a) => a.type === 'investment');
    accounts.value = investmentAccounts;
  } catch (err: any) {
    notificationsStore.addNotification({
      type: 'error',
      message: err.data?.message || 'Erreur de chargement',
    });
  } finally {
    loading.value = false;
  }
};

const openSellModal = (position: Position) => {
  selectedPosition.value = position;
  sellQuantity.value = 1;
  sellAccountId.value = '';
  showSellModal.value = true;
};

const handleSell = async () => {
  if (!sellAccountId.value || !selectedPosition.value) return;

  try {
    sellLoading.value = true;
    await apiFetch('/investment/orders', {
      method: 'POST',
      body: {
        accountId: sellAccountId.value,
        stockId: selectedPosition.value.stockId,
        orderType: 'SELL',
        quantity: Number(sellQuantity.value),
      },
    });

    notificationsStore.addNotification({
      type: 'success',
      message: 'Ordre de vente passé avec succès !',
    });

    showSellModal.value = false;
    await loadData();
  } catch (err: any) {
    notificationsStore.addNotification({
      type: 'error',
      message: err.data?.message || 'Erreur lors de la vente',
    });
  } finally {
    sellLoading.value = false;
  }
};

onMounted(() => {
  loadData();
});
</script>
