// Interface/web/next/app/reset-password/page.tsx
"use client";

import { useState, useEffect, Suspense } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import Link from "next/link";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import axios from "axios";
import { useAuth } from "@/components/contexts/AuthContext";
import { resetPasswordSchema, ResetPasswordFormData } from "@/components/lib/validations/schemas";
import '@flaticon/flaticon-uicons/css/all/all.css';

function ResetPasswordContent() {
	const router = useRouter();
	const searchParams = useSearchParams();
	const token = searchParams.get("token");
	const { loading: authLoading, isAuthenticated } = useAuth();
	const [loading, setLoading] = useState(false);
	const [success, setSuccess] = useState(false);
	const [error, setError] = useState("");

	const {
		register,
		handleSubmit,
		formState: { errors },
	} = useForm<ResetPasswordFormData>({
		resolver: zodResolver(resetPasswordSchema),
	});

	useEffect(() => {
		if (!token) {
			setError("Token de réinitialisation manquant");
		}
	}, [token]);

	useEffect(() => {
			if (isAuthenticated) {
				router.push("/dashboard");
				return;
			}
		}, [authLoading, isAuthenticated, router]);

	const onSubmit = async (data: ResetPasswordFormData) => {
		if (!token) {
			setError("Token de réinitialisation manquant");
			return;
		}

		setLoading(true);
		setError("");

		try {
			const response = await axios.post(
				"http://localhost:3001/api/users/reset-password",
				{
					token,
					newPassword: data.password,
				}
			);

			if (response.data.success) {
				setSuccess(true);
				setTimeout(() => {
					router.push("/login");
				}, 3000);
			}
		} catch (err: any) {
			setError(
				err.response?.data?.error ||
					"Une erreur est survenue. Veuillez réessayer."
			);
		} finally {
			setLoading(false);
		}
	};

	return (
		<div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-purple-600 to-blue-500 px-4">
			<div className="max-w-md w-full bg-white rounded-lg shadow-xl p-8">
				<div className="text-center mb-8">
					<h1 className="text-3xl font-bold text-gray-900 mb-2 flex items-center justify-center gap-2">
						<i className="fi fi-rr-key"></i>
						Nouveau mot de passe
					</h1>
					<p className="text-gray-600">
						Définissez un nouveau mot de passe pour votre compte
					</p>
				</div>

				{success ? (
					<div className="bg-green-50 border border-green-200 text-green-700 px-4 py-3 rounded mb-6">
						<p className="font-medium flex items-center gap-2">
							<i className="fi fi-rr-check-circle"></i>
							Mot de passe réinitialisé !
						</p>
						<p className="text-sm mt-1">
							Redirection vers la page de connexion...
						</p>
					</div>
				) : (
					<form onSubmit={handleSubmit(onSubmit)} className="space-y-6">
						{error && (
							<div className="bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded">
								{error}
							</div>
						)}

						<div>
							<label
								htmlFor="password"
								className="block text-sm font-medium text-gray-700 mb-1"
							>
								Nouveau mot de passe
							</label>
							<input
								type="password"
								id="password"
								{...register("password")}
								className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-purple-500 focus:border-transparent"
								placeholder="••••••••"
							/>
							{errors.password && (
								<p className="text-red-500 text-sm mt-1">
									{errors.password.message}
								</p>
							)}
						</div>

						<div>
							<label
								htmlFor="confirmPassword"
								className="block text-sm font-medium text-gray-700 mb-1"
							>
								Confirmer le mot de passe
							</label>
							<input
								type="password"
								id="confirmPassword"
								{...register("confirmPassword")}
								className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-purple-500 focus:border-transparent"
								placeholder="••••••••"
							/>
							{errors.confirmPassword && (
								<p className="text-red-500 text-sm mt-1">
									{errors.confirmPassword.message}
								</p>
							)}
						</div>

						<button
							type="submit"
							disabled={loading || !token}
							className="w-full bg-purple-600 text-white py-2 rounded-lg hover:bg-purple-700 transition disabled:opacity-50 disabled:cursor-not-allowed font-medium"
						>
							{loading ? "Réinitialisation..." : "Réinitialiser le mot de passe"}
						</button>
					</form>
				)}

				<div className="mt-6 text-center text-sm text-gray-600">
					<Link href="/login" className="text-purple-600 hover:underline">
						← Retour à la connexion
					</Link>
				</div>
			</div>
		</div>
	);
}

export default function ResetPasswordPage() {
	return (
		<Suspense fallback={<div>Chargement...</div>}>
			<ResetPasswordContent />
		</Suspense>
	);
}

// Interface/web/nuxt/pages/reset-password.vue
<template>
  <NuxtLayout name="auth">
    <div class="max-w-md w-full bg-white rounded-lg shadow-xl p-8">
      <div class="text-center mb-8">
        <h1 class="text-3xl font-bold text-gray-900 mb-2 flex items-center justify-center gap-2">
          <Icon name="heroicons:key" class="w-8 h-8" />
          Nouveau mot de passe
        </h1>
        <p class="text-gray-600">Définissez un nouveau mot de passe pour votre compte</p>
      </div>

      <UiAlert v-if="success" variant="success" class="mb-6">
        <p class="font-medium flex items-center gap-2">
          <Icon name="heroicons:check-circle" class="w-5 h-5" />
          Mot de passe réinitialisé !
        </p>
        <p class="text-sm mt-1">Redirection vers la page de connexion...</p>
      </UiAlert>

      <form v-if="!success" @submit.prevent="handleSubmit" class="space-y-6">
        <UiAlert v-if="error" variant="danger" :closable="true" @close="error = ''">
          {{ error }}
        </UiAlert>

        <UiInput
          v-model="formData.password"
          label="Nouveau mot de passe"
          type="password"
          placeholder="••••••••"
          :error="errors.password"
          required
        />

        <UiInput
          v-model="formData.confirmPassword"
          label="Confirmer le mot de passe"
          type="password"
          placeholder="••••••••"
          :error="errors.confirmPassword"
          required
        />

        <UiButton
          type="submit"
          variant="primary"
          size="lg"
          :loading="loading"
          :disabled="!token"
          class="w-full"
        >
          Réinitialiser le mot de passe
        </UiButton>
      </form>

      <div class="mt-6 text-center text-sm text-gray-600">
        <NuxtLink to="/login" class="text-purple-600 hover:underline">
          ← Retour à la connexion
        </NuxtLink>
      </div>
    </div>
  </NuxtLayout>
</template>

<script setup lang="ts">
import { resetPasswordSchema, type ResetPasswordFormData } from '~/utils/validation';

definePageMeta({
  layout: false,
});

const route = useRoute();
const router = useRouter();
const authStore = useAuthStore();
const { apiFetch } = useApi();
const notificationsStore = useNotificationsStore();

const token = route.query.token as string | undefined;

const formData = ref<ResetPasswordFormData>({
  password: '',
  confirmPassword: '',
});

const errors = ref<Partial<Record<keyof ResetPasswordFormData, string>>>({});
const error = ref('');
const success = ref(false);
const loading = ref(false);

// Vérifier le token au montage
onMounted(() => {
  if (!token) {
    error.value = 'Token de réinitialisation manquant';
  }

  // Rediriger si déjà authentifié
  if (authStore.isAuthenticated) {
    router.push('/dashboard');
  }
});

const handleSubmit = async () => {
  errors.value = {};
  error.value = '';

  if (!token) {
    error.value = 'Token de réinitialisation manquant';
    return;
  }

  // Validation avec Zod
  const result = resetPasswordSchema.safeParse(formData.value);
  if (!result.success) {
    result.error.issues.forEach((issue) => {
      if (issue.path[0]) {
        errors.value[issue.path[0] as keyof ResetPasswordFormData] = issue.message;
      }
    });
    return;
  }

  loading.value = true;

  try {
    await apiFetch('/users/reset-password', {
      method: 'POST',
      body: {
        token,
        newPassword: formData.value.password,
      },
    });

    success.value = true;
    notificationsStore.addNotification({
      type: 'success',
      message: 'Mot de passe réinitialisé avec succès !',
    });

    setTimeout(() => {
      router.push('/login');
    }, 3000);
  } catch (err: any) {
    const errorMessage =
      err.data?.message || err.message || 'Une erreur est survenue. Veuillez réessayer.';
    error.value = errorMessage;
    notificationsStore.addNotification({
      type: 'error',
      message: errorMessage,
    });
  } finally {
    loading.value = false;
  }
};
</script>
