// Interface/web/next/app/admin/news/[id]/page.tsx
"use client";

import React, { useState, useEffect } from "react";
import { useAuth } from "../../../../components/contexts/AuthContext";
import { newsService, News, UpdateNewsDTO } from "../../../../components/lib/api/news.service";
import { useRouter } from "next/navigation";
import Link from "next/link";
import '@flaticon/flaticon-uicons/css/all/all.css';

interface EditAdminNewsPageProps {
	params: Promise<{
		id: string;
	}>;
}

/**
 * Page d'édition d'actualité pour les directeurs
 */
export default function EditAdminNewsPage({ params }: EditAdminNewsPageProps) {
	const unwrappedParams = React.use(params);
	const { user } = useAuth();
	const router = useRouter();
	const [news, setNews] = useState<News | null>(null);
	const [formData, setFormData] = useState<UpdateNewsDTO>({
		title: "",
		content: "",
		published: false,
	});
	const [loading, setLoading] = useState(true);
	const [saving, setSaving] = useState(false);
	const [error, setError] = useState<string | null>(null);

	useEffect(() => {
		loadNews();
	}, [unwrappedParams.id]);

	const loadNews = async () => {
		try {
			setLoading(true);
			setError(null);
			const response = await newsService.getById(unwrappedParams.id);
			
			if (response.success && response.data) {
				setNews(response.data);
				setFormData({
					title: response.data.title,
					content: response.data.content,
					published: response.data.published,
				});
			} else {
				setError(response.message || "Actualité introuvable");
			}
		} catch (err) {
			console.error("Erreur lors du chargement:", err);
			setError("Une erreur inattendue s'est produite");
		} finally {
			setLoading(false);
		}
	};

	const handleInputChange = (
		e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>
	) => {
		const { name, value, type } = e.target;
		setFormData((prev) => ({
			...prev,
			[name]: type === "checkbox" ? (e.target as HTMLInputElement).checked : value,
		}));
	};

	const handleSubmit = async (e: React.FormEvent, publish?: boolean) => {
		e.preventDefault();
		setError(null);
		setSaving(true);

		try {
			const dataToSubmit = {
				...formData,
				published: publish !== undefined ? publish : formData.published,
			};

			const response = await newsService.update(unwrappedParams.id, dataToSubmit);

			if (response.success) {
				router.push("/admin/news");
			} else {
				setError(response.message || "Erreur lors de la mise à jour");
			}
		} catch (err) {
			console.error("Erreur lors de la mise à jour:", err);
			setError("Une erreur inattendue s'est produite");
		} finally {
			setSaving(false);
		}
	};

	if (loading) {
		return (
			<div className="min-h-screen bg-linear-to-br from-purple-50 to-purple-100 flex items-center justify-center">
				<div className="text-center">
					<div className="animate-spin rounded-full h-12 w-12 border-b-2 border-purple-600 mx-auto"></div>
					<p className="mt-4 text-gray-600">Chargement de l'actualité...</p>
				</div>
			</div>
		);
	}

	if (error && !news) {
		return (
			<div className="min-h-screen bg-linear-to-br from-purple-50 to-purple-100 flex items-center justify-center">
				<div className="text-center">
					<i className="fi fi-rr-exclamation mx-auto text-6xl text-gray-400"></i>
					<h3 className="mt-2 text-sm font-medium text-gray-900">Actualité introuvable</h3>
					<p className="mt-1 text-sm text-gray-500">{error}</p>
					<div className="mt-6">
						<Link
							href="/admin/news"
							className="inline-flex items-center px-4 py-2 bg-purple-600 text-white rounded-lg hover:bg-purple-700 transition-colors"
						>
							Retour aux actualités
						</Link>
					</div>
				</div>
			</div>
		);
	}

	return (
		<div className="min-h-screen bg-linear-to-br from-purple-50 to-purple-100">
			<div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
				{/* Header */}
				<div className="bg-linear-to-r from-purple-600 to-purple-800 rounded-xl shadow-lg p-8 text-white mb-8">
					<div className="flex items-center justify-between">
						<div>
							<h1 className="text-3xl font-bold mb-2">Modifier l'Actualité (Admin)</h1>
							<p className="text-purple-100">
								Mettez à jour cette actualité officielle
							</p>
							{news && (
								<div className="flex items-center mt-2 space-x-4 text-sm text-purple-100">
									<span>
										Créée le {new Date(news.createdAt).toLocaleDateString("fr-FR")}
									</span>
									{news.updatedAt !== news.createdAt && (
										<span>
											Modifiée le {new Date(news.updatedAt).toLocaleDateString("fr-FR")}
										</span>
									)}
									<span
										className={`px-2 py-1 rounded-full text-xs font-medium ${
											news.published
												? "bg-green-100 text-green-800"
												: "bg-white text-gray-800"
										}`}
									>
										{news.published ? "Publiée" : "Brouillon"}
									</span>
								</div>
							)}
						</div>
						<Link
							href="/admin/news"
							className="bg-white text-purple-600 px-4 py-2 rounded-lg font-semibold hover:bg-purple-50 transition-colors flex items-center space-x-2"
						>
							<i className="fi fi-rr-arrow-left w-5 h-5"></i>
							<span>Retour</span>
						</Link>
					</div>
				</div>

				{/* Form */}
				<div className="bg-white rounded-lg shadow-md p-8">
				{error && (
					<div className="bg-red-50 border border-red-200 rounded-lg p-4 mb-6">
						<div className="flex items-center">
							<i className="fi fi-rr-exclamation text-xl text-red-600 mr-2"></i>
							<p className="text-red-800">{error}</p>
						</div>
					</div>
				)}					<form onSubmit={handleSubmit} className="space-y-6">
						{/* Title */}
						<div>
							<label
								htmlFor="title"
								className="block text-sm font-medium text-gray-700 mb-2"
							>
								Titre de l'actualité <span className="text-red-500">*</span>
							</label>
							<input
								type="text"
								id="title"
								name="title"
								value={formData.title}
								onChange={handleInputChange}
								required
								maxLength={255}
								className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-purple-500 focus:border-purple-500 transition-colors"
								placeholder="Entrez le titre de l'actualité..."
							/>
						</div>

						{/* Content */}
						<div>
							<label
								htmlFor="content"
								className="block text-sm font-medium text-gray-700 mb-2"
							>
								Contenu <span className="text-red-500">*</span>
							</label>
							<textarea
								id="content"
								name="content"
								value={formData.content}
								onChange={handleInputChange}
								required
								rows={12}
								className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-purple-500 focus:border-purple-500 transition-colors resize-vertical"
								placeholder="Rédigez le contenu de votre actualité..."
							/>
						</div>

						{/* Actions */}
						<div className="flex items-center justify-between pt-6 border-t border-gray-200">
							<div className="text-sm text-gray-600">
								<span className="text-red-500">*</span> Champs obligatoires
							</div>
							<div className="flex items-center space-x-4">
								{formData.published ? (
									// Si déjà publié, proposer de dépublier et de sauvegarder
									<>
										<button
											type="button"
											onClick={(e) => handleSubmit(e, false)}
											disabled={saving || !formData.title.trim() || !formData.content.trim()}
											className="px-6 py-3 bg-gray-600 text-white rounded-lg hover:bg-gray-700 disabled:opacity-50 disabled:cursor-not-allowed transition-colors flex items-center space-x-2"
										>
											{saving ? (
												<div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white"></div>
											) : (
												<i className="fi fi-rr-eye-crossed w-5 h-5"></i>
											)}
											<span>Dépublier</span>
										</button>
										<button
											type="submit"
											disabled={saving || !formData.title.trim() || !formData.content.trim()}
											className="px-6 py-3 bg-purple-600 text-white rounded-lg hover:bg-purple-700 disabled:opacity-50 disabled:cursor-not-allowed transition-colors flex items-center space-x-2"
										>
											{saving ? (
												<div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white"></div>
											) : (
												<i className="fi fi-rr-upload w-5 h-5"></i>
											)}
											<span>Mettre à jour</span>
										</button>
									</>
								) : (
									// Si brouillon, proposer de sauvegarder et de publier
									<>
										<button
											type="submit"
											disabled={saving || !formData.title.trim() || !formData.content.trim()}
											className="px-6 py-3 bg-gray-600 text-white rounded-lg hover:bg-gray-700 disabled:opacity-50 disabled:cursor-not-allowed transition-colors flex items-center space-x-2"
										>
											{saving ? (
												<div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white"></div>
											) : (
												<i className="fi fi-rr-disk w-5 h-5"></i>
											)}
											<span>Sauvegarder</span>
										</button>
										<button
											type="button"
											onClick={(e) => handleSubmit(e, true)}
											disabled={saving || !formData.title.trim() || !formData.content.trim()}
											className="px-6 py-3 bg-purple-600 text-white rounded-lg hover:bg-purple-700 disabled:opacity-50 disabled:cursor-not-allowed transition-colors flex items-center space-x-2"
										>
											{saving ? (
												<div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white"></div>
											) : (
												<i className="fi fi-rr-check-circle w-5 h-5"></i>
											)}
											<span>Publier</span>
										</button>
									</>
								)}
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	);
}

// Interface/web/nuxt/pages/admin/news/[id].vue
<template>
  <NuxtLayout name="dashboard">
    <div class="max-w-4xl mx-auto">
      <NuxtLink
        to="/admin/news"
        class="text-purple-600 hover:text-purple-700 font-medium flex items-center gap-2 mb-6"
      >
        <Icon name="heroicons:arrow-left" class="w-5 h-5" />
        Retour aux actualités
      </NuxtLink>

      <h1 class="text-3xl font-bold text-gray-900 mb-8">Modifier l'actualité</h1>

      <div v-if="loading" class="text-center py-12">
        <Icon name="svg-spinners:ring-resize" class="w-16 h-16 mx-auto text-purple-600" />
      </div>

      <UiCard v-else-if="article" padding="lg">
        <form @submit.prevent="handleSubmit" class="space-y-6">
          <UiInput
            v-model="formData.title"
            label="Titre"
            type="text"
            required
          />

          <UiInput v-model="formData.category" label="Catégorie" type="select" required>
            <select v-model="formData.category" class="w-full px-4 py-2 border rounded-lg">
              <option value="Économie">Économie</option>
              <option value="Finance">Finance</option>
              <option value="Investissement">Investissement</option>
              <option value="Banque">Banque</option>
              <option value="Réglementation">Réglementation</option>
            </select>
          </UiInput>

          <UiInput v-model="formData.summary" label="Résumé" type="textarea">
            <textarea
              v-model="formData.summary"
              rows="3"
              class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-purple-500 focus:border-transparent"
            ></textarea>
          </UiInput>

          <UiInput v-model="formData.content" label="Contenu" type="textarea">
            <textarea
              v-model="formData.content"
              rows="10"
              class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-purple-500 focus:border-transparent"
            ></textarea>
          </UiInput>

          <UiInput
            v-model="formData.imageUrl"
            label="URL de l'image"
            type="text"
          />

          <div class="flex gap-4">
            <UiButton type="submit" variant="primary" size="lg" :loading="saving" class="flex-1">
              Enregistrer les modifications
            </UiButton>
            <UiButton variant="ghost" size="lg" @click="router.push('/admin/news')">
              Annuler
            </UiButton>
          </div>
        </form>
      </UiCard>
    </div>
  </NuxtLayout>
</template>

<script setup lang="ts">
definePageMeta({
  layout: false,
  middleware: ['auth', 'role'],
  role: 'director',
});

const route = useRoute();
const router = useRouter();
const { apiFetch } = useApi();
const notificationsStore = useNotificationsStore();

const newsId = route.params.id as string;

interface News {
  id: string;
  title: string;
  category: string;
  summary: string;
  content: string;
  imageUrl?: string;
}

const article = ref<News | null>(null);
const loading = ref(true);
const saving = ref(false);

const formData = ref({
  title: '',
  category: '',
  summary: '',
  content: '',
  imageUrl: '',
});

const loadArticle = async () => {
  try {
    loading.value = true;
    const data = await apiFetch<News>(`/news/${newsId}`);
    article.value = data;
    formData.value = {
      title: data.title,
      category: data.category,
      summary: data.summary,
      content: data.content,
      imageUrl: data.imageUrl || '',
    };
  } catch (err: any) {
    notificationsStore.addNotification({
      type: 'error',
      message: err.data?.message || 'Erreur de chargement',
    });
    router.push('/admin/news');
  } finally {
    loading.value = false;
  }
};

const handleSubmit = async () => {
  saving.value = true;

  try {
    await apiFetch(`/news/${newsId}`, {
      method: 'PUT',
      body: formData.value,
    });

    notificationsStore.addNotification({
      type: 'success',
      message: 'Actualité modifiée avec succès',
    });

    router.push('/admin/news');
  } catch (err: any) {
    notificationsStore.addNotification({
      type: 'error',
      message: err.data?.message || 'Erreur lors de la modification',
    });
  } finally {
    saving.value = false;
  }
};

onMounted(() => {
  loadArticle();
});
</script>
